"""
platinum_data.py - name tables for Pokemon Platinum (USA), indexed by the
game's own IDs.

Generated from the pret/pokeplatinum decompilation (generated/species.txt,
moves.txt, items.txt, natures.txt, map_headers.txt, include/data/map_headers.h
and res/text/location_names.json). Names are derived from the constant names,
so a few differ slightly from the in-game spelling.
"""

BADGES = ['Coal', 'Forest', 'Cobble', 'Fen', 'Relic', 'Mine', 'Icicle', 'Beacon']

# Gen IV status condition bits (party data +0x88 / battle mon +0x6C).
STATUS_BITS = [(0x07, 'Asleep'), (0x08, 'Poisoned'), (0x10, 'Burned'),
               (0x20, 'Frozen'), (0x40, 'Paralyzed'), (0x80, 'Badly poisoned')]

# FaceDirection in the saved Location struct.
DIRECTIONS = ['up', 'down', 'left', 'right']

# Trainer classes seen in battle data +0x3C6 (the RetroAchievements notes call
# them sprite IDs). 0x3F is the rival class; the parser shows the rival's
# real name from the save instead.
TRAINER_SPRITES = {
    0x00: 'Lucas', 0x01: 'Dawn', 0x3E: 'Roark', 0x3F: 'Barry', 0x40: 'Byron',
    0x41: 'Aaron', 0x42: 'Bertha', 0x43: 'Flint', 0x44: 'Lucian',
    0x45: 'Cynthia', 0x48: 'Mars', 0x4A: 'Gardenia', 0x4B: 'Crasher Wake',
    0x4C: 'Maylene', 0x4D: 'Fantina', 0x4E: 'Candice', 0x4F: 'Volkner',
    0x56: 'Cyrus', 0x57: 'Jupiter', 0x58: 'Saturn', 0x5A: 'Cheryl',
    0x5B: 'Riley', 0x5C: 'Marley', 0x5D: 'Buck', 0x5E: 'Mira',
}

# Music IDs at 0x021BEB04 (RetroAchievements code notes). Not complete.
MUSIC = {
    0x400: 'Route theme', 0x424: 'Underground', 0x42D: 'Pal Park',
    0x434: 'Pokemon League', 0x45A: 'Piano before Cynthia',
    0x45C: 'Wild battle', 0x45D: 'Gym battle', 0x45F: 'Trainer battle',
    0x462: 'Cynthia battle', 0x464: 'Rival battle',
    0x467: 'Wild Pokemon defeated', 0x468: 'Trainer victory',
    0x469: 'Gym victory', 0x46A: 'Cynthia victory', 0x470: 'Elite Four battle',
    0x475: 'Evolution', 0x47E: 'Poke Radar', 0x492: 'Trade', 0x493: 'Hall of Fame',
    0x494: 'Intro', 0x495: 'Title screen', 0x497: 'Wi-Fi jingle',
    0x4A9: 'Battle Castle',
}
BATTLE_MUSIC = {0x45C, 0x45D, 0x45F, 0x462, 0x464, 0x470}

SPECIES = [
    '-', 'Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon',
    'Charizard', 'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie', 'Metapod',
    'Butterfree', 'Weedle', 'Kakuna', 'Beedrill', 'Pidgey', 'Pidgeotto',
    'Pidgeot', 'Rattata', 'Raticate', 'Spearow', 'Fearow', 'Ekans',
    'Arbok', 'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash', 'Nidoran F',
    'Nidorina', 'Nidoqueen', 'Nidoran M', 'Nidorino', 'Nidoking', 'Clefairy',
    'Clefable', 'Vulpix', 'Ninetales', 'Jigglypuff', 'Wigglytuff', 'Zubat',
    'Golbat', 'Oddish', 'Gloom', 'Vileplume', 'Paras', 'Parasect',
    'Venonat', 'Venomoth', 'Diglett', 'Dugtrio', 'Meowth', 'Persian',
    'Psyduck', 'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine',
    'Poliwag', 'Poliwhirl', 'Poliwrath', 'Abra', 'Kadabra', 'Alakazam',
    'Machop', 'Machoke', 'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel',
    'Tentacool', 'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta',
    'Rapidash', 'Slowpoke', 'Slowbro', 'Magnemite', 'Magneton', "Farfetch'd",
    'Doduo', 'Dodrio', 'Seel', 'Dewgong', 'Grimer', 'Muk',
    'Shellder', 'Cloyster', 'Gastly', 'Haunter', 'Gengar', 'Onix',
    'Drowzee', 'Hypno', 'Krabby', 'Kingler', 'Voltorb', 'Electrode',
    'Exeggcute', 'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
    'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
    'Tangela', 'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Seaking',
    'Staryu', 'Starmie', 'Mr. Mime', 'Scyther', 'Jynx', 'Electabuzz',
    'Magmar', 'Pinsir', 'Tauros', 'Magikarp', 'Gyarados', 'Lapras',
    'Ditto', 'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon',
    'Omanyte', 'Omastar', 'Kabuto', 'Kabutops', 'Aerodactyl', 'Snorlax',
    'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair', 'Dragonite',
    'Mewtwo', 'Mew', 'Chikorita', 'Bayleef', 'Meganium', 'Cyndaquil',
    'Quilava', 'Typhlosion', 'Totodile', 'Croconaw', 'Feraligatr', 'Sentret',
    'Furret', 'Hoothoot', 'Noctowl', 'Ledyba', 'Ledian', 'Spinarak',
    'Ariados', 'Crobat', 'Chinchou', 'Lanturn', 'Pichu', 'Cleffa',
    'Igglybuff', 'Togepi', 'Togetic', 'Natu', 'Xatu', 'Mareep',
    'Flaaffy', 'Ampharos', 'Bellossom', 'Marill', 'Azumarill', 'Sudowoodo',
    'Politoed', 'Hoppip', 'Skiploom', 'Jumpluff', 'Aipom', 'Sunkern',
    'Sunflora', 'Yanma', 'Wooper', 'Quagsire', 'Espeon', 'Umbreon',
    'Murkrow', 'Slowking', 'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig',
    'Pineco', 'Forretress', 'Dunsparce', 'Gligar', 'Steelix', 'Snubbull',
    'Granbull', 'Qwilfish', 'Scizor', 'Shuckle', 'Heracross', 'Sneasel',
    'Teddiursa', 'Ursaring', 'Slugma', 'Magcargo', 'Swinub', 'Piloswine',
    'Corsola', 'Remoraid', 'Octillery', 'Delibird', 'Mantine', 'Skarmory',
    'Houndour', 'Houndoom', 'Kingdra', 'Phanpy', 'Donphan', 'Porygon2',
    'Stantler', 'Smeargle', 'Tyrogue', 'Hitmontop', 'Smoochum', 'Elekid',
    'Magby', 'Miltank', 'Blissey', 'Raikou', 'Entei', 'Suicune',
    'Larvitar', 'Pupitar', 'Tyranitar', 'Lugia', 'Ho-Oh', 'Celebi',
    'Treecko', 'Grovyle', 'Sceptile', 'Torchic', 'Combusken', 'Blaziken',
    'Mudkip', 'Marshtomp', 'Swampert', 'Poochyena', 'Mightyena', 'Zigzagoon',
    'Linoone', 'Wurmple', 'Silcoon', 'Beautifly', 'Cascoon', 'Dustox',
    'Lotad', 'Lombre', 'Ludicolo', 'Seedot', 'Nuzleaf', 'Shiftry',
    'Taillow', 'Swellow', 'Wingull', 'Pelipper', 'Ralts', 'Kirlia',
    'Gardevoir', 'Surskit', 'Masquerain', 'Shroomish', 'Breloom', 'Slakoth',
    'Vigoroth', 'Slaking', 'Nincada', 'Ninjask', 'Shedinja', 'Whismur',
    'Loudred', 'Exploud', 'Makuhita', 'Hariyama', 'Azurill', 'Nosepass',
    'Skitty', 'Delcatty', 'Sableye', 'Mawile', 'Aron', 'Lairon',
    'Aggron', 'Meditite', 'Medicham', 'Electrike', 'Manectric', 'Plusle',
    'Minun', 'Volbeat', 'Illumise', 'Roselia', 'Gulpin', 'Swalot',
    'Carvanha', 'Sharpedo', 'Wailmer', 'Wailord', 'Numel', 'Camerupt',
    'Torkoal', 'Spoink', 'Grumpig', 'Spinda', 'Trapinch', 'Vibrava',
    'Flygon', 'Cacnea', 'Cacturne', 'Swablu', 'Altaria', 'Zangoose',
    'Seviper', 'Lunatone', 'Solrock', 'Barboach', 'Whiscash', 'Corphish',
    'Crawdaunt', 'Baltoy', 'Claydol', 'Lileep', 'Cradily', 'Anorith',
    'Armaldo', 'Feebas', 'Milotic', 'Castform', 'Kecleon', 'Shuppet',
    'Banette', 'Duskull', 'Dusclops', 'Tropius', 'Chimecho', 'Absol',
    'Wynaut', 'Snorunt', 'Glalie', 'Spheal', 'Sealeo', 'Walrein',
    'Clamperl', 'Huntail', 'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon',
    'Shelgon', 'Salamence', 'Beldum', 'Metang', 'Metagross', 'Regirock',
    'Regice', 'Registeel', 'Latias', 'Latios', 'Kyogre', 'Groudon',
    'Rayquaza', 'Jirachi', 'Deoxys', 'Turtwig', 'Grotle', 'Torterra',
    'Chimchar', 'Monferno', 'Infernape', 'Piplup', 'Prinplup', 'Empoleon',
    'Starly', 'Staravia', 'Staraptor', 'Bidoof', 'Bibarel', 'Kricketot',
    'Kricketune', 'Shinx', 'Luxio', 'Luxray', 'Budew', 'Roserade',
    'Cranidos', 'Rampardos', 'Shieldon', 'Bastiodon', 'Burmy', 'Wormadam',
    'Mothim', 'Combee', 'Vespiquen', 'Pachirisu', 'Buizel', 'Floatzel',
    'Cherubi', 'Cherrim', 'Shellos', 'Gastrodon', 'Ambipom', 'Drifloon',
    'Drifblim', 'Buneary', 'Lopunny', 'Mismagius', 'Honchkrow', 'Glameow',
    'Purugly', 'Chingling', 'Stunky', 'Skuntank', 'Bronzor', 'Bronzong',
    'Bonsly', 'Mime Jr.', 'Happiny', 'Chatot', 'Spiritomb', 'Gible',
    'Gabite', 'Garchomp', 'Munchlax', 'Riolu', 'Lucario', 'Hippopotas',
    'Hippowdon', 'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak', 'Carnivine',
    'Finneon', 'Lumineon', 'Mantyke', 'Snover', 'Abomasnow', 'Weavile',
    'Magnezone', 'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire', 'Magmortar',
    'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon', 'Gliscor', 'Mamoswine',
    'Porygon-Z', 'Gallade', 'Probopass', 'Dusknoir', 'Froslass', 'Rotom',
    'Uxie', 'Mesprit', 'Azelf', 'Dialga', 'Palkia', 'Heatran',
    'Regigigas', 'Giratina', 'Cresselia', 'Phione', 'Manaphy', 'Darkrai',
    'Shaymin', 'Arceus', 'Egg', 'Bad Egg',
]

MOVES = [
    '-', 'Pound', 'Karate Chop', 'Double Slap', 'Comet Punch', 'Mega Punch',
    'Pay Day', 'Fire Punch', 'Ice Punch', 'Thunder Punch', 'Scratch', 'Vice Grip',
    'Guillotine', 'Razor Wind', 'Swords Dance', 'Cut', 'Gust', 'Wing Attack',
    'Whirlwind', 'Fly', 'Bind', 'Slam', 'Vine Whip', 'Stomp',
    'Double Kick', 'Mega Kick', 'Jump Kick', 'Rolling Kick', 'Sand Attack', 'Headbutt',
    'Horn Attack', 'Fury Attack', 'Horn Drill', 'Tackle', 'Body Slam', 'Wrap',
    'Take Down', 'Thrash', 'Double-Edge', 'Tail Whip', 'Poison Sting', 'Twineedle',
    'Pin Missile', 'Leer', 'Bite', 'Growl', 'Roar', 'Sing',
    'Supersonic', 'Sonic Boom', 'Disable', 'Acid', 'Ember', 'Flamethrower',
    'Mist', 'Water Gun', 'Hydro Pump', 'Surf', 'Ice Beam', 'Blizzard',
    'Psybeam', 'Bubble Beam', 'Aurora Beam', 'Hyper Beam', 'Peck', 'Drill Peck',
    'Submission', 'Low Kick', 'Counter', 'Seismic Toss', 'Strength', 'Absorb',
    'Mega Drain', 'Leech Seed', 'Growth', 'Razor Leaf', 'Solar Beam', 'Poison Powder',
    'Stun Spore', 'Sleep Powder', 'Petal Dance', 'String Shot', 'Dragon Rage', 'Fire Spin',
    'ThunderShock', 'Thunderbolt', 'Thunder Wave', 'Thunder', 'Rock Throw', 'Earthquake',
    'Fissure', 'Dig', 'Toxic', 'Confusion', 'Psychic', 'Hypnosis',
    'Meditate', 'Agility', 'Quick Attack', 'Rage', 'Teleport', 'Night Shade',
    'Mimic', 'Screech', 'Double Team', 'Recover', 'Harden', 'Minimize',
    'Smoke Screen', 'Confuse Ray', 'Withdraw', 'Defense Curl', 'Barrier', 'Light Screen',
    'Haze', 'Reflect', 'Focus Energy', 'Bide', 'Metronome', 'Mirror Move',
    'Selfdestruct', 'Egg Bomb', 'Lick', 'Smog', 'Sludge', 'Bone Club',
    'Fire Blast', 'Waterfall', 'Clamp', 'Swift', 'Skull Bash', 'Spike Cannon',
    'Constrict', 'Amnesia', 'Kinesis', 'Softboiled', 'Hi Jump Kick', 'Glare',
    'Dream Eater', 'Poison Gas', 'Barrage', 'Leech Life', 'Lovely Kiss', 'Sky Attack',
    'Transform', 'Bubble', 'Dizzy Punch', 'Spore', 'Flash', 'Psywave',
    'Splash', 'Acid Armor', 'Crabhammer', 'Explosion', 'Fury Swipes', 'Bonemerang',
    'Rest', 'Rock Slide', 'Hyper Fang', 'Sharpen', 'Conversion', 'Tri Attack',
    'Super Fang', 'Slash', 'Substitute', 'Struggle', 'Sketch', 'Triple Kick',
    'Thief', 'Spider Web', 'Mind Reader', 'Nightmare', 'Flame Wheel', 'Snore',
    'Curse', 'Flail', 'Conversion 2', 'Aeroblast', 'Cotton Spore', 'Reversal',
    'Spite', 'Powder Snow', 'Protect', 'Mach Punch', 'Scary Face', 'Faint Attack',
    'Sweet Kiss', 'Belly Drum', 'Sludge Bomb', 'Mud-Slap', 'Octazooka', 'Spikes',
    'Zap Cannon', 'Foresight', 'Destiny Bond', 'Perish Song', 'Icy Wind', 'Detect',
    'Bone Rush', 'Lock-On', 'Outrage', 'Sandstorm', 'Giga Drain', 'Endure',
    'Charm', 'Rollout', 'False Swipe', 'Swagger', 'Milk Drink', 'Spark',
    'Fury Cutter', 'Steel Wing', 'Mean Look', 'Attract', 'Sleep Talk', 'Heal Bell',
    'Return', 'Present', 'Frustration', 'Safeguard', 'Pain Split', 'Sacred Fire',
    'Magnitude', 'Dynamic Punch', 'Megahorn', 'Dragon Breath', 'Baton Pass', 'Encore',
    'Pursuit', 'Rapid Spin', 'Sweet Scent', 'Iron Tail', 'Metal Claw', 'Vital Throw',
    'Morning Sun', 'Synthesis', 'Moonlight', 'Hidden Power', 'Cross Chop', 'Twister',
    'Rain Dance', 'Sunny Day', 'Crunch', 'Mirror Coat', 'Psych Up', 'Extreme Speed',
    'Ancient Power', 'Shadow Ball', 'Future Sight', 'Rock Smash', 'Whirlpool', 'Beat Up',
    'Fake Out', 'Uproar', 'Stockpile', 'Spit Up', 'Swallow', 'Heat Wave',
    'Hail', 'Torment', 'Flatter', 'Will-O-Wisp', 'Memento', 'Facade',
    'Focus Punch', 'Smelling Salt', 'Follow Me', 'Nature Power', 'Charge', 'Taunt',
    'Helping Hand', 'Trick', 'Role Play', 'Wish', 'Assist', 'Ingrain',
    'Superpower', 'Magic Coat', 'Recycle', 'Revenge', 'Brick Break', 'Yawn',
    'Knock Off', 'Endeavor', 'Eruption', 'Skill Swap', 'Imprison', 'Refresh',
    'Grudge', 'Snatch', 'Secret Power', 'Dive', 'Arm Thrust', 'Camouflage',
    'Tail Glow', 'Luster Purge', 'Mist Ball', 'Feather Dance', 'Teeter Dance', 'Blaze Kick',
    'Mud Sport', 'Ice Ball', 'Needle Arm', 'Slack Off', 'Hyper Voice', 'Poison Fang',
    'Crush Claw', 'Blast Burn', 'Hydro Cannon', 'Meteor Mash', 'Astonish', 'Weather Ball',
    'Aromatherapy', 'Fake Tears', 'Air Cutter', 'Overheat', 'Odor Sleuth', 'Rock Tomb',
    'Silver Wind', 'Metal Sound', 'Grass Whistle', 'Tickle', 'Cosmic Power', 'Water Spout',
    'Signal Beam', 'Shadow Punch', 'Extrasensory', 'Sky Uppercut', 'Sand Tomb', 'Sheer Cold',
    'Muddy Water', 'Bullet Seed', 'Aerial Ace', 'Icicle Spear', 'Iron Defense', 'Block',
    'Howl', 'Dragon Claw', 'Frenzy Plant', 'Bulk Up', 'Bounce', 'Mud Shot',
    'Poison Tail', 'Covet', 'Volt Tackle', 'Magical Leaf', 'Water Sport', 'Calm Mind',
    'Leaf Blade', 'Dragon Dance', 'Rock Blast', 'Shock Wave', 'Water Pulse', 'Doom Desire',
    'Psycho Boost', 'Roost', 'Gravity', 'Miracle Eye', 'Wake-Up Slap', 'Hammer Arm',
    'Gyro Ball', 'Healing Wish', 'Brine', 'Natural Gift', 'Feint', 'Pluck',
    'Tailwind', 'Acupressure', 'Metal Burst', 'U-turn', 'Close Combat', 'Payback',
    'Assurance', 'Embargo', 'Fling', 'Psycho Shift', 'Trump Card', 'Heal Block',
    'Wring Out', 'Power Trick', 'Gastro Acid', 'Lucky Chant', 'Me First', 'Copycat',
    'Power Swap', 'Guard Swap', 'Punishment', 'Last Resort', 'Worry Seed', 'Sucker Punch',
    'Toxic Spikes', 'Heart Swap', 'Aqua Ring', 'Magnet Rise', 'Flare Blitz', 'Force Palm',
    'Aura Sphere', 'Rock Polish', 'Poison Jab', 'Dark Pulse', 'Night Slash', 'Aqua Tail',
    'Seed Bomb', 'Air Slash', 'X-Scissor', 'Bug Buzz', 'Dragon Pulse', 'Dragon Rush',
    'Power Gem', 'Drain Punch', 'Vacuum Wave', 'Focus Blast', 'Energy Ball', 'Brave Bird',
    'Earth Power', 'Switcheroo', 'Giga Impact', 'Nasty Plot', 'Bullet Punch', 'Avalanche',
    'Ice Shard', 'Shadow Claw', 'Thunder Fang', 'Ice Fang', 'Fire Fang', 'Shadow Sneak',
    'Mud Bomb', 'Psycho Cut', 'Zen Headbutt', 'Mirror Shot', 'Flash Cannon', 'Rock Climb',
    'Defog', 'Trick Room', 'Draco Meteor', 'Discharge', 'Lava Plume', 'Leaf Storm',
    'Power Whip', 'Rock Wrecker', 'Cross Poison', 'Gunk Shot', 'Iron Head', 'Magnet Bomb',
    'Stone Edge', 'Captivate', 'Stealth Rock', 'Grass Knot', 'Chatter', 'Judgment',
    'Bug Bite', 'Charge Beam', 'Wood Hammer', 'Aqua Jet', 'Attack Order', 'Defend Order',
    'Heal Order', 'Head Smash', 'Double Hit', 'Roar Of Time', 'Spacial Rend', 'Lunar Dance',
    'Crush Grip', 'Magma Storm', 'Dark Void', 'Seed Flare', 'Ominous Wind', 'Shadow Force',
]

ITEMS = [
    '-', 'Master Ball', 'Ultra Ball', 'Great Ball', 'Poke Ball', 'Safari Ball',
    'Net Ball', 'Dive Ball', 'Nest Ball', 'Repeat Ball', 'Timer Ball', 'Luxury Ball',
    'Premier Ball', 'Dusk Ball', 'Heal Ball', 'Quick Ball', 'Cherish Ball', 'Potion',
    'Antidote', 'Burn Heal', 'Ice Heal', 'Awakening', 'Parlyz Heal', 'Full Restore',
    'Max Potion', 'Hyper Potion', 'Super Potion', 'Full Heal', 'Revive', 'Max Revive',
    'Fresh Water', 'Soda Pop', 'Lemonade', 'Moomoo Milk', 'Energypowder', 'Energy Root',
    'Heal Powder', 'Revival Herb', 'Ether', 'Max Ether', 'Elixir', 'Max Elixir',
    'Lava Cookie', 'Berry Juice', 'Sacred Ash', 'Hp Up', 'Protein', 'Iron',
    'Carbos', 'Calcium', 'Rare Candy', 'Pp Up', 'Zinc', 'Pp Max',
    'Old Gateau', 'Guard Spec', 'Dire Hit', 'X Attack', 'X Defense', 'X Speed',
    'X Accuracy', 'X Special', 'X Sp Def', 'Poke Doll', 'Fluffy Tail', 'Blue Flute',
    'Yellow Flute', 'Red Flute', 'Black Flute', 'White Flute', 'Shoal Salt', 'Shoal Shell',
    'Red Shard', 'Blue Shard', 'Yellow Shard', 'Green Shard', 'Super Repel', 'Max Repel',
    'Escape Rope', 'Repel', 'Sun Stone', 'Moon Stone', 'Fire Stone', 'Thunderstone',
    'Water Stone', 'Leaf Stone', 'Tinymushroom', 'Big Mushroom', 'Pearl', 'Big Pearl',
    'Stardust', 'Star Piece', 'Nugget', 'Heart Scale', 'Honey', 'Growth Mulch',
    'Damp Mulch', 'Stable Mulch', 'Gooey Mulch', 'Root Fossil', 'Claw Fossil', 'Helix Fossil',
    'Dome Fossil', 'Old Amber', 'Armor Fossil', 'Skull Fossil', 'Rare Bone', 'Shiny Stone',
    'Dusk Stone', 'Dawn Stone', 'Oval Stone', 'Odd Keystone', 'Griseous Orb', 'Unused 113',
    'Unused 114', 'Unused 115', 'Unused 116', 'Unused 117', 'Unused 118', 'Unused 119',
    'Unused 120', 'Unused 121', 'Unused 122', 'Unused 123', 'Unused 124', 'Unused 125',
    'Unused 126', 'Unused 127', 'Unused 128', 'Unused 129', 'Unused 130', 'Unused 131',
    'Unused 132', 'Unused 133', 'Unused 134', 'Adamant Orb', 'Lustrous Orb', 'Grass Mail',
    'Flame Mail', 'Bubble Mail', 'Bloom Mail', 'Tunnel Mail', 'Steel Mail', 'Heart Mail',
    'Snow Mail', 'Space Mail', 'Air Mail', 'Mosaic Mail', 'Brick Mail', 'Cheri Berry',
    'Chesto Berry', 'Pecha Berry', 'Rawst Berry', 'Aspear Berry', 'Leppa Berry', 'Oran Berry',
    'Persim Berry', 'Lum Berry', 'Sitrus Berry', 'Figy Berry', 'Wiki Berry', 'Mago Berry',
    'Aguav Berry', 'Iapapa Berry', 'Razz Berry', 'Bluk Berry', 'Nanab Berry', 'Wepear Berry',
    'Pinap Berry', 'Pomeg Berry', 'Kelpsy Berry', 'Qualot Berry', 'Hondew Berry', 'Grepa Berry',
    'Tamato Berry', 'Cornn Berry', 'Magost Berry', 'Rabuta Berry', 'Nomel Berry', 'Spelon Berry',
    'Pamtre Berry', 'Watmel Berry', 'Durin Berry', 'Belue Berry', 'Occa Berry', 'Passho Berry',
    'Wacan Berry', 'Rindo Berry', 'Yache Berry', 'Chople Berry', 'Kebia Berry', 'Shuca Berry',
    'Coba Berry', 'Payapa Berry', 'Tanga Berry', 'Charti Berry', 'Kasib Berry', 'Haban Berry',
    'Colbur Berry', 'Babiri Berry', 'Chilan Berry', 'Liechi Berry', 'Ganlon Berry', 'Salac Berry',
    'Petaya Berry', 'Apicot Berry', 'Lansat Berry', 'Starf Berry', 'Enigma Berry', 'Micle Berry',
    'Custap Berry', 'Jaboca Berry', 'Rowap Berry', 'Brightpowder', 'White Herb', 'Macho Brace',
    'Exp Share', 'Quick Claw', 'Soothe Bell', 'Mental Herb', 'Choice Band', 'Kings Rock',
    'Silverpowder', 'Amulet Coin', 'Cleanse Tag', 'Soul Dew', 'Deepseatooth', 'Deepseascale',
    'Smoke Ball', 'Everstone', 'Focus Band', 'Lucky Egg', 'Scope Lens', 'Metal Coat',
    'Leftovers', 'Dragon Scale', 'Light Ball', 'Soft Sand', 'Hard Stone', 'Miracle Seed',
    'Blackglasses', 'Black Belt', 'Magnet', 'Mystic Water', 'Sharp Beak', 'Poison Barb',
    'Nevermeltice', 'Spell Tag', 'Twistedspoon', 'Charcoal', 'Dragon Fang', 'Silk Scarf',
    'Upgrade', 'Shell Bell', 'Sea Incense', 'Lax Incense', 'Lucky Punch', 'Metal Powder',
    'Thick Club', 'Stick', 'Red Scarf', 'Blue Scarf', 'Pink Scarf', 'Green Scarf',
    'Yellow Scarf', 'Wide Lens', 'Muscle Band', 'Wise Glasses', 'Expert Belt', 'Light Clay',
    'Life Orb', 'Power Herb', 'Toxic Orb', 'Flame Orb', 'Quick Powder', 'Focus Sash',
    'Zoom Lens', 'Metronome', 'Iron Ball', 'Lagging Tail', 'Destiny Knot', 'Black Sludge',
    'Icy Rock', 'Smooth Rock', 'Heat Rock', 'Damp Rock', 'Grip Claw', 'Choice Scarf',
    'Sticky Barb', 'Power Bracer', 'Power Belt', 'Power Lens', 'Power Band', 'Power Anklet',
    'Power Weight', 'Shed Shell', 'Big Root', 'Choice Specs', 'Flame Plate', 'Splash Plate',
    'Zap Plate', 'Meadow Plate', 'Icicle Plate', 'Fist Plate', 'Toxic Plate', 'Earth Plate',
    'Sky Plate', 'Mind Plate', 'Insect Plate', 'Stone Plate', 'Spooky Plate', 'Draco Plate',
    'Dread Plate', 'Iron Plate', 'Odd Incense', 'Rock Incense', 'Full Incense', 'Wave Incense',
    'Rose Incense', 'Luck Incense', 'Pure Incense', 'Protector', 'Electirizer', 'Magmarizer',
    'Dubious Disc', 'Reaper Cloth', 'Razor Claw', 'Razor Fang', 'Tm01', 'Tm02',
    'Tm03', 'Tm04', 'Tm05', 'Tm06', 'Tm07', 'Tm08',
    'Tm09', 'Tm10', 'Tm11', 'Tm12', 'Tm13', 'Tm14',
    'Tm15', 'Tm16', 'Tm17', 'Tm18', 'Tm19', 'Tm20',
    'Tm21', 'Tm22', 'Tm23', 'Tm24', 'Tm25', 'Tm26',
    'Tm27', 'Tm28', 'Tm29', 'Tm30', 'Tm31', 'Tm32',
    'Tm33', 'Tm34', 'Tm35', 'Tm36', 'Tm37', 'Tm38',
    'Tm39', 'Tm40', 'Tm41', 'Tm42', 'Tm43', 'Tm44',
    'Tm45', 'Tm46', 'Tm47', 'Tm48', 'Tm49', 'Tm50',
    'Tm51', 'Tm52', 'Tm53', 'Tm54', 'Tm55', 'Tm56',
    'Tm57', 'Tm58', 'Tm59', 'Tm60', 'Tm61', 'Tm62',
    'Tm63', 'Tm64', 'Tm65', 'Tm66', 'Tm67', 'Tm68',
    'Tm69', 'Tm70', 'Tm71', 'Tm72', 'Tm73', 'Tm74',
    'Tm75', 'Tm76', 'Tm77', 'Tm78', 'Tm79', 'Tm80',
    'Tm81', 'Tm82', 'Tm83', 'Tm84', 'Tm85', 'Tm86',
    'Tm87', 'Tm88', 'Tm89', 'Tm90', 'Tm91', 'Tm92',
    'Hm01', 'Hm02', 'Hm03', 'Hm04', 'Hm05', 'Hm06',
    'Hm07', 'Hm08', 'Explorer Kit', 'Loot Sack', 'Rule Book', 'Poke Radar',
    'Point Card', 'Journal', 'Seal Case', 'Fashion Case', 'Seal Bag', 'Pal Pad',
    'Works Key', 'Old Charm', 'Galactic Key', 'Red Chain', 'Town Map', 'Vs Seeker',
    'Coin Case', 'Old Rod', 'Good Rod', 'Super Rod', 'Sprayduck', 'Poffin Case',
    'Bicycle', 'Suite Key', 'Oaks Letter', 'Lunar Wing', 'Member Card', 'Azure Flute',
    'S S Ticket', 'Contest Pass', 'Magma Stone', 'Parcel', 'Coupon 1', 'Coupon 2',
    'Coupon 3', 'Storage Key', 'Secretpotion', 'Vs Recorder', 'Gracidea', 'Secret Key',
]

NATURES = [
    'Hardy', 'Lonely', 'Brave', 'Adamant', 'Naughty',
    'Bold', 'Docile', 'Relaxed', 'Impish', 'Lax',
    'Timid', 'Hasty', 'Serious', 'Jolly', 'Naive',
    'Modest', 'Mild', 'Quiet', 'Bashful', 'Rash',
    'Calm', 'Gentle', 'Sassy', 'Careful', 'Quirky',

]

# (location name shown in game, map header name) per map ID
MAPS = [
    ('Mystery Zone', 'Everywhere'),
    ('Mystery Zone', 'Nothing'),
    ('Mystery Zone', 'Underground'),
    ('Jubilife City', 'Jubilife City'),
    ('Jubilife City', 'Jubilife City Mart'),
    ('Jubilife City', 'Unused Jubilife City House 1'),
    ('Jubilife City', 'Jubilife City Pokecenter 1F'),
    ('Jubilife City', 'Jubilife City Pokecenter 2F'),
    ('Pokétch Co.', 'Poketch Co 1F'),
    ('Pokétch Co.', 'Poketch Co 2F'),
    ('Pokétch Co.', 'Poketch Co 3F'),
    ('Jubilife TV', 'Jubilife TV 1F'),
    ('Jubilife TV', 'Jubilife TV 2F'),
    ('Jubilife TV', 'Jubilife TV 3F'),
    ('Jubilife TV', 'Jubilife TV 4F'),
    ('Jubilife TV', 'Jubilife TV 2F Gallery'),
    ('Jubilife TV', 'Jubilife TV 3F Global Ranking Room'),
    ('Jubilife TV', 'Jubilife TV 3F Group Ranking Room'),
    ('Jubilife TV', 'Jubilife TV Elevator'),
    ('Jubilife City', 'Jubilife City South House 1F'),
    ('Jubilife City', 'Jubilife City South House 2F'),
    ('Jubilife City', 'Unused Jubilife City South House 3F'),
    ('Jubilife City', 'Unused Jubilife City South House 4F'),
    ('Jubilife City', 'Unused Jubilife City House 2'),
    ('Jubilife City', 'Jubilife City Condominiums 1F'),
    ('Jubilife City', 'Jubilife City Condominiums 2F'),
    ('Jubilife City', 'Unused Jubilife City Condominiums 3F'),
    ('Jubilife City', 'Unused Jubilife City Condominiums 4F'),
    ('Global Terminal', 'Global Terminal 1F'),
    ('Trainers’ School', 'Trainers School'),
    ('Jubilife City', 'Jubilife City Southwest House 1F'),
    ('Jubilife City', 'Unused Jubilife City House 3'),
    ('Jubilife City', 'Unused Jubilife City House 4'),
    ('Canalave City', 'Canalave City'),
    ('Canalave City', 'Canalave City Mart'),
    ('Canalave City', 'Canalave City Gym'),
    ('Canalave City', 'Canalave City Pokecenter 1F'),
    ('Canalave City', 'Canalave City Pokecenter 2F'),
    ('Canalave Library', 'Canalave Library 1F'),
    ('Canalave Library', 'Canalave Library 2F'),
    ('Canalave Library', 'Canalave Library 3F'),
    ('Canalave City', 'Canalave City Southeast House'),
    ('Canalave City', 'Canalave City East House'),
    ('Canalave City', 'Canalave City Harbor Inn'),
    ('Canalave City', 'Canalave City Sailor Eldritch House'),
    ('Oreburgh City', 'Oreburgh City'),
    ('Oreburgh City', 'Oreburgh City Mart'),
    ('Oreburgh City', 'Oreburgh City Gym'),
    ('Oreburgh City', 'Oreburgh City Pokecenter 1F'),
    ('Oreburgh City', 'Oreburgh City Pokecenter 2F'),
    ('Oreburgh City', 'Oreburgh City Northwest House 1F'),
    ('Oreburgh City', 'Oreburgh City Northwest House 2F'),
    ('Oreburgh City', 'Unused Oreburgh City Northwest House 3F'),
    ('Oreburgh City', 'Unused Oreburgh City Northwest House 4F'),
    ('Oreburgh City', 'Oreburgh City North House 1F'),
    ('Oreburgh City', 'Oreburgh City North House 2F'),
    ('Oreburgh City', 'Unused Oreburgh City North House 3F'),
    ('Oreburgh City', 'Unused Oreburgh City North House 4F'),
    ('Oreburgh City', 'Oreburgh City Middle House'),
    ('Mining Museum', 'Mining Museum'),
    ('Oreburgh City', 'Oreburgh City West House'),
    ('Oreburgh City', 'Oreburgh City East House 1F'),
    ('Oreburgh City', 'Oreburgh City East House 2F'),
    ('Oreburgh City', 'Unused Oreburgh City East House 3F'),
    ('Oreburgh City', 'Oreburgh City South House'),
    ('Eterna City', 'Eterna City'),
    ('Eterna City', 'Eterna City Mart'),
    ('Eterna City', 'Eterna City Gym'),
    ('Eterna City', 'Eterna City Dp Gym'),
    ('Eterna City', 'Eterna City Pokecenter 1F'),
    ('Eterna City', 'Eterna City Pokecenter 2F'),
    ('Cycle Shop', 'Cycle Shop'),
    ('T.G. Eterna Bldg', 'Team Galactic Eterna Building 1F'),
    ('T.G. Eterna Bldg', 'Team Galactic Eterna Building 2F'),
    ('T.G. Eterna Bldg', 'Team Galactic Eterna Building 3F'),
    ('T.G. Eterna Bldg', 'Team Galactic Eterna Building 4F'),
    ('Eterna City', 'Eterna City Condominiums 1F'),
    ('Eterna City', 'Eterna City Condominiums 2F'),
    ('Eterna City', 'Eterna City Condominiums 3F'),
    ('Eterna City', 'Unused Eterna City Condominiums 4F'),
    ('Route 206', 'Route 206 Cycling Road North Gate'),
    ('Eterna City', 'Eterna City Herb Shop'),
    ('Eterna City', 'Eterna City South House'),
    ('Eterna City', 'Eterna City East House'),
    ('Eterna City', 'Eterna City Underground Man House'),
    ('Eterna City', 'Unused Eterna City House'),
    ('Hearthome City', 'Hearthome City'),
    ('Hearthome City', 'Hearthome City Mart'),
    ('Hearthome City', 'Hearthome City Gym Entrance Room'),
    ('Hearthome City', 'Hearthome City Gym Trainer Room 1'),
    ('Hearthome City', 'Hearthome City Gym Trainer Room 2'),
    ('Hearthome City', 'Hearthome City Gym Leader Room'),
    ('Hearthome City', 'Hearthome City Dp Gym Trainer Room 1'),
    ('Hearthome City', 'Hearthome City Dp Gym Elevator Room 1'),
    ('Hearthome City', 'Hearthome City Dp Gym Trainer Room 2'),
    ('Hearthome City', 'Hearthome City Dp Gym Elevator Room 2'),
    ('Hearthome City', 'Hearthome City Dp Gym Trainer Room 3'),
    ('Hearthome City', 'Hearthome City Dp Gym Trainer Room 4'),
    ('Hearthome City', 'Hearthome City Dp Gym Trainer Room 5'),
    ('Hearthome City', 'Hearthome City Dp Gym Trainer Room 6'),
    ('Hearthome City', 'Hearthome City Dp Gym Leader Room'),
    ('Hearthome City', 'Hearthome City Pokecenter 1F'),
    ('Hearthome City', 'Hearthome City Pokecenter 2F'),
    ('Hearthome City', 'Hearthome City Southeast House 1F'),
    ('Hearthome City', 'Hearthome City Southeast House 2F'),
    ('Hearthome City', 'Hearthome City Southeast House Elevator'),
    ('Hearthome City', 'Hearthome City Pokemon Fan Club'),
    ('Hearthome City', 'Hearthome City West Gate To Amity Square'),
    ('Hearthome City', 'Hearthome City East Gate To Amity Square'),
    ('Route 208', 'Route 208 Gate To Hearthome City'),
    ('Route 209', 'Route 209 Gate To Hearthome City'),
    ('Route 212', 'Route 212 Gate To Hearthome City'),
    ('Hearthome City', 'Hearthome City Northeast House 1F'),
    ('Hearthome City', 'Hearthome City Northeast House 2F'),
    ('Hearthome City', 'Hearthome City Northeast House Elevator'),
    ('Hearthome City', 'Hearthome City Northwest House'),
    ('Poffin House', 'Poffin House'),
    ('Contest Hall', 'Contest Hall Lobby'),
    ('Contest Hall', 'Contest Hall Stage Ongoing Contest'),
    ('Foreign Building', 'Foreign Building'),
    ('Pastoria City', 'Pastoria City'),
    ('Pastoria City', 'Pastoria City Mart'),
    ('Pastoria City', 'Pastoria City Gym'),
    ('Pastoria City', 'Pastoria City Pokecenter 1F'),
    ('Pastoria City', 'Pastoria City Pokecenter 2F'),
    ('Pastoria City', 'Pastoria City Observatory Gate 1F'),
    ('Pastoria City', 'Pastoria City Observatory Gate 2F'),
    ('Pastoria City', 'Pastoria City Southwest House'),
    ('Pastoria City', 'Pastoria City Middle House'),
    ('Pastoria City', 'Pastoria City East House'),
    ('Pastoria City', 'Pastoria City North House'),
    ('Pastoria City', 'Pastoria City Northeast House'),
    ('Veilstone City', 'Veilstone City'),
    ('Veilstone City', 'Veilstone City Gym'),
    ('Veilstone City', 'Veilstone City Pokecenter 1F'),
    ('Veilstone City', 'Veilstone City Pokecenter 2F'),
    ('Game Corner', 'Game Corner'),
    ('Veilstone Store', 'Veilstone Store 1F'),
    ('Veilstone Store', 'Veilstone Store 2F'),
    ('Veilstone Store', 'Veilstone Store 3F'),
    ('Veilstone Store', 'Veilstone Store 4F'),
    ('Veilstone Store', 'Veilstone Store 5F'),
    ('Veilstone Store', 'Veilstone Store Elevator'),
    ('Veilstone City', 'Veilstone City Galactic Warehouse'),
    ('Veilstone City', 'Veilstone City Prize Exchange'),
    ('Veilstone City', 'Veilstone City Southeast House'),
    ('Veilstone City', 'Veilstone City Northwest House'),
    ('Veilstone City', 'Veilstone City Northeast House'),
    ('Veilstone City', 'Veilstone City Southwest House'),
    ('Route 215', 'Route 215 Gate To Veilstone City'),
    ('Sunyshore City', 'Sunyshore City'),
    ('Sunyshore City', 'Sunyshore City Pokecenter 1F'),
    ('Sunyshore City', 'Sunyshore City Pokecenter 2F'),
    ('Sunyshore City', 'Sunyshore City Mart'),
    ('Sunyshore City', 'Sunyshore City Gym Room 1'),
    ('Sunyshore City', 'Sunyshore City Gym Room 2'),
    ('Sunyshore City', 'Sunyshore City Gym Room 3'),
    ('Sunyshore Market', 'Sunyshore Market'),
    ('Sunyshore City', 'Sunyshore City Northeast House'),
    ('Sunyshore City', 'Sunyshore City West House'),
    ('Sunyshore City', 'Sunyshore City Northwest House'),
    ('Sunyshore City', 'Unused Sunyshore City House 1'),
    ('Sunyshore City', 'Unused Sunyshore City House 2'),
    ('Sunyshore City', 'Sunyshore City East House'),
    ('Vista Lighthouse', 'Vista Lighthouse'),
    ('Snowpoint City', 'Snowpoint City'),
    ('Snowpoint City', 'Snowpoint City Mart'),
    ('Snowpoint City', 'Snowpoint City Gym'),
    ('Snowpoint City', 'Snowpoint City Pokecenter 1F'),
    ('Snowpoint City', 'Snowpoint City Pokecenter 2F'),
    ('Snowpoint City', 'Snowpoint City West House'),
    ('Snowpoint City', 'Snowpoint City East House'),
    ('Pokémon League', 'Pokemon League'),
    ('Pokémon League', 'Pokemon League South Pokecenter 1F'),
    ('Pokémon League', 'Pokemon League South Pokecenter 2F'),
    ('Pokémon League', 'Pokemon League North Pokecenter 1F'),
    ('Pokémon League', 'Pokemon League Elevator To Aaron Room'),
    ('Pokémon League', 'Pokemon League Aaron Room'),
    ('Pokémon League', 'Pokemon League Elevator To Bertha Room'),
    ('Pokémon League', 'Pokemon League Bertha Room'),
    ('Pokémon League', 'Pokemon League Elevator To Flint Room'),
    ('Pokémon League', 'Pokemon League Flint Room'),
    ('Pokémon League', 'Pokemon League Elevator To Lucian Room'),
    ('Pokémon League', 'Pokemon League Lucian Room'),
    ('Pokémon League', 'Pokemon League Elevator To Champion Room'),
    ('Pokémon League', 'Pokemon League Champion Room'),
    ('Pokémon League', 'Pokemon League Hallway To Hall Of Fame'),
    ('Pokémon League', 'Pokemon League Hall Of Fame'),
    ('Fight Area', 'Fight Area'),
    ('Fight Area', 'Fight Area Pokecenter 1F'),
    ('Fight Area', 'Fight Area Pokecenter 2F'),
    ('Fight Area', 'Fight Area Mart'),
    ('Battle Park', 'Unused Battle Park Gate To Fight Area'),
    ('Route 225', 'Route 225 Gate To Fight Area'),
    ('Fight Area', 'Fight Area Middle House'),
    ('Fight Area', 'Fight Area South House'),
    ('Mystery Zone', 'Unused Fight Area House'),
    ('Oreburgh Mine', 'Unknown 197'),
    ('Oreburgh Mine', 'Oreburgh Mine B1F'),
    ('Oreburgh Mine', 'Oreburgh Mine B2F'),
    ('Valley Windworks', 'Valley Windworks Outside'),
    ('Valley Windworks', 'Valley Windworks Building'),
    ('Eterna Forest', 'Eterna Forest Outside'),
    ('Eterna Forest', 'Eterna Forest'),
    ('Fuego Ironworks', 'Fuego Ironworks Outside'),
    ('Fuego Ironworks', 'Fuego Ironworks Building'),
    ('Mystery Zone', 'Unknown 206'),
    ('Mt. Coronet', 'Mt Coronet 1F South'),
    ('Mt. Coronet', 'Mt Coronet 2F'),
    ('Mt. Coronet', 'Mt Coronet 3F'),
    ('Mt. Coronet', 'Mt Coronet Outside North'),
    ('Mt. Coronet', 'Mt Coronet Outside South'),
    ('Mt. Coronet', 'Mt Coronet 4F Rooms 1 And 2'),
    ('Mt. Coronet', 'Mt Coronet 4F Room 3'),
    ('Mt. Coronet', 'Mt Coronet 5F'),
    ('Mt. Coronet', 'Mt Coronet 6F'),
    ('Mt. Coronet', 'Mt Coronet 1F Tunnel Room'),
    ('Mt. Coronet', 'Mt Coronet 1F North Room 2'),
    ('Mt. Coronet', 'Mt Coronet 1F North Room 1'),
    ('Mt. Coronet', 'Mt Coronet B1F'),
    ('Spear Pillar', 'Spear Pillar'),
    ('Spear Pillar', 'Spear Pillar Distorted'),
    ('Mystery Zone', 'Unknown 222'),
    ('Pastoria City', 'Pastoria City Dp Great Marsh'),
    ('Mystery Zone', 'Unknown 224'),
    ('Solaceon Ruins', 'Solaceon Ruins Maniac Tunnel Room'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 1'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 2 Northeast Dead End'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 1 Northwest Dead End'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 2'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 1 Southeast Dead End'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 3'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 2 Southeast Dead End'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 6 Southeast Dead End'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 5 Southwest Dead End'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 3 Northwest Dead End'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 3 Southwest Dead End'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 4'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 6'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 5'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 7'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 4 Southeast Dead End'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 6 Northwest Dead End'),
    ('Mystery Zone', 'Unknown 243'),
    ('Victory Road', 'Victory Road 1F'),
    ('Victory Road', 'Victory Road 2F'),
    ('Victory Road', 'Victory Road B1F'),
    ('Victory Road', 'Victory Road 1F Room 2'),
    ('Victory Road', 'Victory Road 1F Room 1'),
    ('Victory Road', 'Victory Road 1F Room 3'),
    ('Mystery Zone', 'Unknown 250'),
    ('Pal Park', 'Pal Park'),
    ('Mystery Zone', 'Unknown 252'),
    ('Amity Square', 'Amity Square'),
    ('Ravaged Path', 'Ravaged Path'),
    ('Mystery Zone', 'Unknown 255'),
    ('Floaroma Meadow', 'Floaroma Meadow'),
    ('Floaroma Meadow', 'Floaroma Meadow House'),
    ('Oreburgh Gate', 'Oreburgh Gate 1F'),
    ('Oreburgh Gate', 'Oreburgh Gate B1F'),
    ('Fullmoon Island', 'Fullmoon Island'),
    ('Fullmoon Island', 'Fullmoon Island Forest'),
    ('Stark Mountain', 'Stark Mountain Outside'),
    ('Stark Mountain', 'Stark Mountain Room 1'),
    ('Stark Mountain', 'Stark Mountain Room 2'),
    ('Stark Mountain', 'Stark Mountain Room 3'),
    ('Mystery Zone', 'Unknown 266'),
    ('Sendoff Spring', 'Sendoff Spring'),
    ('Turnback Cave', 'Turnback Cave Entrance'),
    ('Turnback Cave', 'Turnback Cave Pillar Room'),
    ('Turnback Cave', 'Turnback Cave Giratina Room'),
    ('Turnback Cave', 'Turnback Cave Pillar 1 Room 1'),
    ('Turnback Cave', 'Turnback Cave Pillar 1 Room 2'),
    ('Turnback Cave', 'Turnback Cave Pillar 1 Room 3'),
    ('Flower Paradise', 'Flower Paradise'),
    ('Mystery Zone', 'Unknown 275'),
    ('Mystery Zone', 'Unknown 276'),
    ('Mystery Zone', 'Unknown 277'),
    ('Snowpoint Temple', 'Snowpoint Temple 1F'),
    ('Snowpoint Temple', 'Snowpoint Temple B1F'),
    ('Snowpoint Temple', 'Snowpoint Temple B2F'),
    ('Snowpoint Temple', 'Snowpoint Temple B3F'),
    ('Snowpoint Temple', 'Snowpoint Temple B4F'),
    ('Snowpoint Temple', 'Snowpoint Temple B5F'),
    ('Wayward Cave', 'Wayward Cave 1F'),
    ('Wayward Cave', 'Wayward Cave B1F'),
    ('Ruin Maniac Cave', 'Ruin Maniac Cave Short'),
    ('Trophy Garden', 'Trophy Garden'),
    ('Iron Island', 'Iron Island'),
    ('Iron Island', 'Iron Island 1F'),
    ('Iron Island', 'Iron Island B1F Left Room'),
    ('Iron Island', 'Iron Island B1F Right Room'),
    ('Iron Island', 'Iron Island B2F Right Room'),
    ('Iron Island', 'Iron Island B2F Left Room'),
    ('Iron Island', 'Iron Island B3F'),
    ('Old Chateau', 'Old Chateau'),
    ('Old Chateau', 'Old Chateau Dining Area'),
    ('Old Chateau', 'Old Chateau Side Rooms'),
    ('Old Chateau', 'Old Chateau Corridor'),
    ('Old Chateau', 'Old Chateau Back West Room'),
    ('Old Chateau', 'Old Chateau Back Middle West Room'),
    ('Old Chateau', 'Old Chateau Back Middle Room'),
    ('Old Chateau', 'Old Chateau Back Middle East Room'),
    ('Old Chateau', 'Old Chateau Back East Room'),
    ('Mystery Zone', 'Unknown 304'),
    ('Galactic HQ', 'Galactic Hq 1F'),
    ('Galactic HQ', 'Galactic Hq 2F'),
    ('Galactic HQ', 'Galactic Hq 3F'),
    ('Galactic HQ', 'Galactic Hq 4F'),
    ('Galactic HQ', 'Galactic Hq B1F'),
    ('Galactic HQ', 'Galactic Hq B2F'),
    ('Lake Verity', 'Lake Verity Low Water'),
    ('Lake Verity', 'Lake Verity'),
    ('Verity Cavern', 'Verity Cavern'),
    ('Lake Valor', 'Lake Valor Drained'),
    ('Lake Valor', 'Lake Valor'),
    ('Valor Cavern', 'Valor Cavern'),
    ('Lake Acuity', 'Lake Acuity Low Water'),
    ('Lake Acuity', 'Lake Acuity'),
    ('Acuity Cavern', 'Acuity Cavern'),
    ('Newmoon Island', 'Newmoon Island'),
    ('Newmoon Island', 'Newmoon Island Forest'),
    ('Battle Park', 'Unused Battle Park'),
    ('Battle Park', 'Unused Battle Park Exchange Service Corner'),
    ('Mystery Zone', 'Unknown 324'),
    ('Mystery Zone', 'Unknown 325'),
    ('Battle Tower', 'Battle Tower'),
    ('Battle Tower', 'Battle Tower Elevator'),
    ('Battle Tower', 'Battle Tower Corridor'),
    ('Battle Tower', 'Battle Tower Corridor Multi'),
    ('Battle Tower', 'Battle Tower Battle Room'),
    ('Battle Tower', 'Battle Tower Multi Battle Room'),
    ('Mystery Zone', 'Communication Club Colosseum 2p'),
    ('Mystery Zone', 'Communication Club Colosseum 4p'),
    ('Verity Lakefront', 'Verity Lakefront'),
    ('Verity Lakefront', 'Unused Verity Lakefront House'),
    ('Valor Lakefront', 'Valor Lakefront'),
    ('Restaurant', 'Restaurant'),
    ('Grand Lake', 'Grand Lake Valor Lakefront East House'),
    ('Grand Lake', 'Grand Lake Valor Lakefront West House'),
    ('Acuity Lakefront', 'Acuity Lakefront'),
    ('Spring Path', 'Spring Path'),
    ('Route 201', 'Route 201'),
    ('Route 202', 'Route 202'),
    ('Route 203', 'Route 203'),
    ('Route 204', 'Route 204 South'),
    ('Route 204', 'Route 204 North'),
    ('Route 205', 'Route 205 South'),
    ('Route 205', 'Route 205 House'),
    ('Route 205', 'Route 205 North'),
    ('Route 206', 'Route 206'),
    ('Route 206', 'Route 206 Cycling Road South Gate'),
    ('Mystery Zone', 'Unused Gate Between Eterna City Route 206'),
    ('Route 207', 'Route 207'),
    ('Route 208', 'Route 208'),
    ('Route 208', 'Route 208 House'),
    ('Route 209', 'Route 209'),
    ('Route 209', 'Route 209 Lost Tower 1F'),
    ('Route 209', 'Route 209 Lost Tower 2F'),
    ('Route 209', 'Route 209 Lost Tower 3F'),
    ('Route 209', 'Route 209 Lost Tower 4F'),
    ('Route 209', 'Route 209 Lost Tower 5F'),
    ('Route 210', 'Route 210 South'),
    ('Route 210', 'Route 210 North'),
    ('Route 210', 'Route 210 Grandma Wilma House'),
    ('Route 211', 'Route 211 West'),
    ('Route 211', 'Route 211 East'),
    ('Route 212', 'Route 212 North'),
    ('Pokémon Mansion', 'Pokemon Mansion'),
    ('Pokémon Mansion', 'Pokemon Mansion Maids Room'),
    ('Pokémon Mansion', 'Pokemon Mansion Office'),
    ('Route 212', 'Route 212 South'),
    ('Route 212', 'Route 212 House'),
    ('Route 213', 'Route 213'),
    ('Route 213', 'Route 213 Gate To Pastoria City'),
    ('Footstep House', 'Footstep House'),
    ('Grand Lake', 'Grand Lake Route 213 Lobby'),
    ('Grand Lake', 'Grand Lake Route 213 East House'),
    ('Grand Lake', 'Grand Lake Route 213 Northwest House'),
    ('Grand Lake', 'Grand Lake Route 213 Northeast House'),
    ('Route 214', 'Route 214'),
    ('Route 214', 'Route 214 Gate To Veilstone City'),
    ('Route 215', 'Route 215'),
    ('Route 216', 'Route 216'),
    ('Route 216', 'Route 216 House'),
    ('Route 217', 'Route 217'),
    ('Route 217', 'Route 217 West House'),
    ('Route 217', 'Route 217 Northeast House'),
    ('Route 218', 'Route 218'),
    ('Route 218', 'Route 218 Gate To Jubilife City'),
    ('Route 218', 'Route 218 Gate To Canalave City'),
    ('Route 219', 'Route 219'),
    ('Route 221', 'Route 221'),
    ('Pal Park', 'Pal Park Lobby'),
    ('Route 221', 'Route 221 House'),
    ('Route 222', 'Route 222'),
    ('Route 222', 'Route 222 West House'),
    ('Route 222', 'Route 222 East House'),
    ('Route 222', 'Route 222 Gate To Sunyshore City'),
    ('Route 224', 'Route 224'),
    ('Route 225', 'Route 225'),
    ('Mystery Zone', 'Unknown 401'),
    ('Mystery Zone', 'Unknown 402'),
    ('Route 227', 'Route 227'),
    ('Mystery Zone', 'Unknown 404'),
    ('Mystery Zone', 'Unknown 405'),
    ('Route 228', 'Route 228'),
    ('Route 229', 'Route 229'),
    ('Mystery Zone', 'Unknown 408'),
    ('Mystery Zone', 'Unknown 409'),
    ('Mystery Zone', 'Record Mixing Room'),
    ('Twinleaf Town', 'Twinleaf Town'),
    ('Twinleaf Town', 'Twinleaf Town Rival House 1F'),
    ('Twinleaf Town', 'Twinleaf Town Rival House 2F'),
    ('Twinleaf Town', 'Twinleaf Town Player House 1F'),
    ('Twinleaf Town', 'Twinleaf Town Player House 2F'),
    ('Twinleaf Town', 'Twinleaf Town Northeast House'),
    ('Twinleaf Town', 'Twinleaf Town Southwest House'),
    ('Sandgem Town', 'Sandgem Town'),
    ('Sandgem Town', 'Sandgem Town Mart'),
    ('Sandgem Town', 'Sandgem Town Pokecenter 1F'),
    ('Sandgem Town', 'Sandgem Town Pokecenter 2F'),
    ('Sandgem Town', 'Sandgem Town Pokemon Research Lab'),
    ('Sandgem Town', 'Sandgem Town Counterpart House 1F'),
    ('Sandgem Town', 'Sandgem Town Counterpart House 2F'),
    ('Sandgem Town', 'Sandgem Town House'),
    ('Floaroma Town', 'Floaroma Town'),
    ('Floaroma Town', 'Floaroma Town Mart'),
    ('Floaroma Town', 'Floaroma Town Pokecenter 1F'),
    ('Floaroma Town', 'Floaroma Town Pokecenter 2F'),
    ('Flower Shop', 'Flower Shop'),
    ('Floaroma Town', 'Floaroma Town Southeast House'),
    ('Floaroma Town', 'Floaroma Town Middle House'),
    ('Solaceon Town', 'Solaceon Town'),
    ('Solaceon Town', 'Solaceon Town Mart'),
    ('Solaceon Town', 'Solaceon Town Pokecenter 1F'),
    ('Solaceon Town', 'Solaceon Town Pokecenter 2F'),
    ('Pokémon Day Care', 'Pokemon Day Care'),
    ('Solaceon Town', 'Solaceon Town Northeast House'),
    ('Solaceon Town', 'Solaceon Town Pokemon News Press'),
    ('Solaceon Town', 'Solaceon Town North House'),
    ('Solaceon Town', 'Solaceon Town East House'),
    ('Celestic Town', 'Celestic Town'),
    ('Celestic Town', 'Celestic Town Pokecenter 1F'),
    ('Celestic Town', 'Celestic Town Pokecenter 2F'),
    ('Celestic Town', 'Celestic Town North House'),
    ('Celestic Town', 'Celestic Town Northwest House'),
    ('Celestic Town', 'Celestic Town Northeast House'),
    ('Celestic Town', 'Celestic Town Southwest House'),
    ('Celestic Town', 'Celestic Town Cave'),
    ('Survival Area', 'Survival Area'),
    ('Survival Area', 'Survival Area Mart'),
    ('Survival Area', 'Survival Area Pokecenter 1F'),
    ('Survival Area', 'Survival Area Pokecenter 2F'),
    ('Battleground', 'Battleground'),
    ('Survival Area', 'Survival Area South House'),
    ('Survival Area', 'Survival Area North House'),
    ('Resort Area', 'Resort Area'),
    ('Resort Area', 'Unused Resort Area Mart'),
    ('Resort Area', 'Resort Area Pokecenter 1F'),
    ('Resort Area', 'Resort Area Pokecenter 2F'),
    ('Resort Area', 'Resort Area Ribbon Syndicate 1F'),
    ('Resort Area', 'Resort Area Ribbon Syndicate 2F'),
    ('Resort Area', 'Resort Area Ribbon Syndicate Elevator'),
    ('Villa', 'Villa'),
    ('Resort Area', 'Resort Area House'),
    ('Mystery Zone', 'Union Room'),
    ('Route 220', 'Route 220'),
    ('Route 223', 'Route 223'),
    ('Route 226', 'Route 226'),
    ('Mystery Zone', 'Unknown 470'),
    ('Route 230', 'Route 230'),
    ('Seabreak Path', 'Seabreak Path'),
    ('Mystery Zone', 'Unknown 473'),
    ('Jubilife City', 'Jubilife City Pokecenter B1F'),
    ('Canalave City', 'Canalave City Pokecenter B1F'),
    ('Oreburgh City', 'Oreburgh City Pokecenter B1F'),
    ('Eterna City', 'Eterna City Pokecenter B1F'),
    ('Hearthome City', 'Hearthome City Pokecenter B1F'),
    ('Pastoria City', 'Pastoria City Pokecenter B1F'),
    ('Veilstone City', 'Veilstone City Pokecenter B1F'),
    ('Sunyshore City', 'Sunyshore City Pokecenter B1F'),
    ('Snowpoint City', 'Snowpoint City Pokecenter B1F'),
    ('Pokémon League', 'Pokemon League South Pokecenter B1F'),
    ('Fight Area', 'Fight Area Pokecenter B1F'),
    ('Sandgem Town', 'Sandgem Town Pokecenter B1F'),
    ('Floaroma Town', 'Floaroma Town Pokecenter B1F'),
    ('Solaceon Town', 'Solaceon Town Pokecenter B1F'),
    ('Celestic Town', 'Celestic Town Pokecenter B1F'),
    ('Survival Area', 'Survival Area Pokecenter B1F'),
    ('Resort Area', 'Resort Area Pokecenter B1F'),
    ('Canalave City', 'Canalave City West House'),
    ('Café', 'Cafe'),
    ('Battle Tower', 'Battle Tower Battle Salon'),
    ('Galactic HQ', 'Galactic Hq Control Room'),
    ('Pokémon League', 'Pokemon League North Pokecenter 2F'),
    ('Pokémon League', 'Pokemon League North Pokecenter B1F'),
    ('Galactic HQ', 'Galactic Hq Laboratory'),
    ('Route 225', 'Route 225 House'),
    ('Route 226', 'Route 226 House'),
    ('Route 227', 'Route 227 House'),
    ('Route 228', 'Route 228 Gate To Route 226'),
    ('Route 228', 'Route 228 North House'),
    ('Route 228', 'Route 228 South House'),
    ('Great Marsh', 'Great Marsh 1'),
    ('Great Marsh', 'Great Marsh 2'),
    ('Great Marsh', 'Great Marsh 3'),
    ('Great Marsh', 'Great Marsh 4'),
    ('Great Marsh', 'Great Marsh 5'),
    ('Great Marsh', 'Great Marsh 6'),
    ('Hall of Origin', 'Hall Of Origin'),
    ('Hall of Origin', 'Unknown 511'),
    ('Ruin Maniac Cave', 'Ruin Maniac Cave Long'),
    ('Maniac Tunnel', 'Maniac Tunnel'),
    ('Iron Island', 'Iron Island House'),
    ('Solaceon Ruins', 'Solaceon Ruins Room 5 Southeast Deadend'),
    ('Vista Lighthouse', 'Vista Lighthouse Elevator'),
    ('Jubilife City', 'Jubilife City Southwest House 2F'),
    ('Turnback Cave', 'Turnback Cave Pillar 1 Room 4'),
    ('Turnback Cave', 'Turnback Cave Pillar 1 Room 5'),
    ('Turnback Cave', 'Turnback Cave Pillar 1 Room 6'),
    ('Turnback Cave', 'Turnback Cave Pillar 2 Room 1'),
    ('Turnback Cave', 'Turnback Cave Pillar 2 Room 2'),
    ('Turnback Cave', 'Turnback Cave Pillar 2 Room 3'),
    ('Turnback Cave', 'Turnback Cave Pillar 2 Room 4'),
    ('Turnback Cave', 'Turnback Cave Pillar 2 Room 5'),
    ('Turnback Cave', 'Turnback Cave Pillar 2 Room 6'),
    ('Turnback Cave', 'Turnback Cave Pillar 3 Room 1'),
    ('Turnback Cave', 'Turnback Cave Pillar 3 Room 2'),
    ('Turnback Cave', 'Turnback Cave Pillar 3 Room 3'),
    ('Turnback Cave', 'Turnback Cave Pillar 3 Room 4'),
    ('Turnback Cave', 'Turnback Cave Pillar 3 Room 5'),
    ('Turnback Cave', 'Turnback Cave Pillar 3 Room 6'),
    ('Turnback Cave', 'Unknown 533'),
    ('Turnback Cave', 'Unknown 534'),
    ('Turnback Cave', 'Unknown 535'),
    ('Turnback Cave', 'Unknown 536'),
    ('Turnback Cave', 'Unknown 537'),
    ('Turnback Cave', 'Unknown 538'),
    ('Turnback Cave', 'Unknown 539'),
    ('Turnback Cave', 'Unknown 540'),
    ('Turnback Cave', 'Unknown 541'),
    ('Turnback Cave', 'Unknown 542'),
    ('Turnback Cave', 'Unknown 543'),
    ('Turnback Cave', 'Unknown 544'),
    ('Turnback Cave', 'Unknown 545'),
    ('Turnback Cave', 'Unknown 546'),
    ('Turnback Cave', 'Unknown 547'),
    ('Turnback Cave', 'Unknown 548'),
    ('Turnback Cave', 'Unknown 549'),
    ('Turnback Cave', 'Unknown 550'),
    ('Turnback Cave', 'Unknown 551'),
    ('Turnback Cave', 'Unknown 552'),
    ('Turnback Cave', 'Unknown 553'),
    ('Turnback Cave', 'Unknown 554'),
    ('Turnback Cave', 'Unknown 555'),
    ('Turnback Cave', 'Unknown 556'),
    ('Turnback Cave', 'Unknown 557'),
    ('Contest Hall', 'Contest Hall Stage No Contest'),
    ('Battle Frontier', 'Battle Frontier'),
    ('Battle Frontier', 'Battle Frontier Gate To Fight Area'),
    ('Battle Tower', 'Unknown 561'),
    ('Battle Factory', 'Battle Factory'),
    ('Battle Hall', 'Battle Hall'),
    ('Battle Castle', 'Battle Castle'),
    ('Battle Arcade', 'Battle Arcade'),
    ('Veilstone Store', 'Veilstone Store B1F'),
    ('Global Terminal', 'Global Terminal 2F'),
    ('Global Terminal', 'Global Terminal 3F'),
    ('Galactic HQ', 'Galactic Hq Hall'),
    ('Distortion World', 'Unknown 570'),
    ('ROTOM’s Room', 'Rotoms Room'),
    ('T.G. Eterna Bldg', 'Unknown 572'),
    ('Distortion World', 'Distortion World 1F'),
    ('Distortion World', 'Distortion World B1F'),
    ('Distortion World', 'Distortion World B2F'),
    ('Distortion World', 'Distortion World B3F'),
    ('Distortion World', 'Distortion World B4F'),
    ('Distortion World', 'Unknown 578'),
    ('Distortion World', 'Distortion World B5F'),
    ('Distortion World', 'Distortion World B6F'),
    ('Distortion World', 'Distortion World B7F'),
    ('Distortion World', 'Distortion World Giratina Room'),
    ('Distortion World', 'Distortion World Turnback Cave Room'),
    ('Spear Pillar', 'Spear Pillar Dialga'),
    ('Spear Pillar', 'Spear Pillar Palkia'),
    ('Jubilife City', 'Wifi Plaza Entrance'),
    ('Iron Island', 'Iron Island Iron Ruins'),
    ('Iron Ruins', 'Iron Ruins'),
    ('Mt. Coronet', 'Mt Coronet Iceberg Ruins'),
    ('Iceberg Ruins', 'Iceberg Ruins'),
    ('Route 228', 'Route 228 Rock Peak Ruins'),
    ('Rock Peak Ruins', 'Rock Peak Ruins'),
]

# Move type, category and base PP by move name, generated from the decomp's
# res/moves/*/data.json. Max PP = base + (base // 5) * PP Ups.
MOVE_INFO = {
    'Pound': ('Normal', 'Physical', 35),
    'Karate Chop': ('Fighting', 'Physical', 25),
    'Double Slap': ('Normal', 'Physical', 10),
    'Comet Punch': ('Normal', 'Physical', 15),
    'Mega Punch': ('Normal', 'Physical', 20),
    'Pay Day': ('Normal', 'Physical', 20),
    'Fire Punch': ('Fire', 'Physical', 15),
    'Ice Punch': ('Ice', 'Physical', 15),
    'Thunder Punch': ('Electric', 'Physical', 15),
    'Scratch': ('Normal', 'Physical', 35),
    'Vice Grip': ('Normal', 'Physical', 30),
    'Guillotine': ('Normal', 'Physical', 5),
    'Razor Wind': ('Normal', 'Special', 10),
    'Swords Dance': ('Normal', 'Status', 30),
    'Cut': ('Normal', 'Physical', 30),
    'Gust': ('Flying', 'Special', 35),
    'Wing Attack': ('Flying', 'Physical', 35),
    'Whirlwind': ('Normal', 'Status', 20),
    'Fly': ('Flying', 'Physical', 15),
    'Bind': ('Normal', 'Physical', 20),
    'Slam': ('Normal', 'Physical', 20),
    'Vine Whip': ('Grass', 'Physical', 15),
    'Stomp': ('Normal', 'Physical', 20),
    'Double Kick': ('Fighting', 'Physical', 30),
    'Mega Kick': ('Normal', 'Physical', 5),
    'Jump Kick': ('Fighting', 'Physical', 25),
    'Rolling Kick': ('Fighting', 'Physical', 15),
    'Sand Attack': ('Ground', 'Status', 15),
    'Headbutt': ('Normal', 'Physical', 15),
    'Horn Attack': ('Normal', 'Physical', 25),
    'Fury Attack': ('Normal', 'Physical', 20),
    'Horn Drill': ('Normal', 'Physical', 5),
    'Tackle': ('Normal', 'Physical', 35),
    'Body Slam': ('Normal', 'Physical', 15),
    'Wrap': ('Normal', 'Physical', 20),
    'Take Down': ('Normal', 'Physical', 20),
    'Thrash': ('Normal', 'Physical', 20),
    'Double-Edge': ('Normal', 'Physical', 15),
    'Tail Whip': ('Normal', 'Status', 30),
    'Poison Sting': ('Poison', 'Physical', 35),
    'Twineedle': ('Bug', 'Physical', 20),
    'Pin Missile': ('Bug', 'Physical', 20),
    'Leer': ('Normal', 'Status', 30),
    'Bite': ('Dark', 'Physical', 25),
    'Growl': ('Normal', 'Status', 40),
    'Roar': ('Normal', 'Status', 20),
    'Sing': ('Normal', 'Status', 15),
    'Supersonic': ('Normal', 'Status', 20),
    'Sonic Boom': ('Normal', 'Special', 20),
    'Disable': ('Normal', 'Status', 20),
    'Acid': ('Poison', 'Special', 30),
    'Ember': ('Fire', 'Special', 25),
    'Flamethrower': ('Fire', 'Special', 15),
    'Mist': ('Ice', 'Status', 30),
    'Water Gun': ('Water', 'Special', 25),
    'Hydro Pump': ('Water', 'Special', 5),
    'Surf': ('Water', 'Special', 15),
    'Ice Beam': ('Ice', 'Special', 10),
    'Blizzard': ('Ice', 'Special', 5),
    'Psybeam': ('Psychic', 'Special', 20),
    'Bubble Beam': ('Water', 'Special', 20),
    'Aurora Beam': ('Ice', 'Special', 20),
    'Hyper Beam': ('Normal', 'Special', 5),
    'Peck': ('Flying', 'Physical', 35),
    'Drill Peck': ('Flying', 'Physical', 20),
    'Submission': ('Fighting', 'Physical', 25),
    'Low Kick': ('Fighting', 'Physical', 20),
    'Counter': ('Fighting', 'Physical', 20),
    'Seismic Toss': ('Fighting', 'Physical', 20),
    'Strength': ('Normal', 'Physical', 15),
    'Absorb': ('Grass', 'Special', 25),
    'Mega Drain': ('Grass', 'Special', 15),
    'Leech Seed': ('Grass', 'Status', 10),
    'Growth': ('Normal', 'Status', 40),
    'Razor Leaf': ('Grass', 'Physical', 25),
    'Solar Beam': ('Grass', 'Special', 10),
    'Poison Powder': ('Poison', 'Status', 35),
    'Stun Spore': ('Grass', 'Status', 30),
    'Sleep Powder': ('Grass', 'Status', 15),
    'Petal Dance': ('Grass', 'Special', 20),
    'String Shot': ('Bug', 'Status', 40),
    'Dragon Rage': ('Dragon', 'Special', 10),
    'Fire Spin': ('Fire', 'Special', 15),
    'ThunderShock': ('Electric', 'Special', 30),
    'Thunderbolt': ('Electric', 'Special', 15),
    'Thunder Wave': ('Electric', 'Status', 20),
    'Thunder': ('Electric', 'Special', 10),
    'Rock Throw': ('Rock', 'Physical', 15),
    'Earthquake': ('Ground', 'Physical', 10),
    'Fissure': ('Ground', 'Physical', 5),
    'Dig': ('Ground', 'Physical', 10),
    'Toxic': ('Poison', 'Status', 10),
    'Confusion': ('Psychic', 'Special', 25),
    'Psychic': ('Psychic', 'Special', 10),
    'Hypnosis': ('Psychic', 'Status', 20),
    'Meditate': ('Psychic', 'Status', 40),
    'Agility': ('Psychic', 'Status', 30),
    'Quick Attack': ('Normal', 'Physical', 30),
    'Rage': ('Normal', 'Physical', 20),
    'Teleport': ('Psychic', 'Status', 20),
    'Night Shade': ('Ghost', 'Special', 15),
    'Mimic': ('Normal', 'Status', 10),
    'Screech': ('Normal', 'Status', 40),
    'Double Team': ('Normal', 'Status', 15),
    'Recover': ('Normal', 'Status', 10),
    'Harden': ('Normal', 'Status', 30),
    'Minimize': ('Normal', 'Status', 20),
    'Smoke Screen': ('Normal', 'Status', 20),
    'Confuse Ray': ('Ghost', 'Status', 10),
    'Withdraw': ('Water', 'Status', 40),
    'Defense Curl': ('Normal', 'Status', 40),
    'Barrier': ('Psychic', 'Status', 30),
    'Light Screen': ('Psychic', 'Status', 30),
    'Haze': ('Ice', 'Status', 30),
    'Reflect': ('Psychic', 'Status', 20),
    'Focus Energy': ('Normal', 'Status', 30),
    'Bide': ('Normal', 'Physical', 10),
    'Metronome': ('Normal', 'Status', 10),
    'Mirror Move': ('Flying', 'Status', 20),
    'Selfdestruct': ('Normal', 'Physical', 5),
    'Egg Bomb': ('Normal', 'Physical', 10),
    'Lick': ('Ghost', 'Physical', 30),
    'Smog': ('Poison', 'Special', 20),
    'Sludge': ('Poison', 'Special', 20),
    'Bone Club': ('Ground', 'Physical', 20),
    'Fire Blast': ('Fire', 'Special', 5),
    'Waterfall': ('Water', 'Physical', 15),
    'Clamp': ('Water', 'Physical', 10),
    'Swift': ('Normal', 'Special', 20),
    'Skull Bash': ('Normal', 'Physical', 15),
    'Spike Cannon': ('Normal', 'Physical', 15),
    'Constrict': ('Normal', 'Physical', 35),
    'Amnesia': ('Psychic', 'Status', 20),
    'Kinesis': ('Psychic', 'Status', 15),
    'Softboiled': ('Normal', 'Status', 10),
    'Hi Jump Kick': ('Fighting', 'Physical', 20),
    'Glare': ('Normal', 'Status', 30),
    'Dream Eater': ('Psychic', 'Special', 15),
    'Poison Gas': ('Poison', 'Status', 40),
    'Barrage': ('Normal', 'Physical', 20),
    'Leech Life': ('Bug', 'Physical', 15),
    'Lovely Kiss': ('Normal', 'Status', 10),
    'Sky Attack': ('Flying', 'Physical', 5),
    'Transform': ('Normal', 'Status', 10),
    'Bubble': ('Water', 'Special', 30),
    'Dizzy Punch': ('Normal', 'Physical', 10),
    'Spore': ('Grass', 'Status', 15),
    'Flash': ('Normal', 'Status', 20),
    'Psywave': ('Psychic', 'Special', 15),
    'Splash': ('Normal', 'Status', 40),
    'Acid Armor': ('Poison', 'Status', 40),
    'Crabhammer': ('Water', 'Physical', 10),
    'Explosion': ('Normal', 'Physical', 5),
    'Fury Swipes': ('Normal', 'Physical', 15),
    'Bonemerang': ('Ground', 'Physical', 10),
    'Rest': ('Psychic', 'Status', 10),
    'Rock Slide': ('Rock', 'Physical', 10),
    'Hyper Fang': ('Normal', 'Physical', 15),
    'Sharpen': ('Normal', 'Status', 30),
    'Conversion': ('Normal', 'Status', 30),
    'Tri Attack': ('Normal', 'Special', 10),
    'Super Fang': ('Normal', 'Physical', 10),
    'Slash': ('Normal', 'Physical', 20),
    'Substitute': ('Normal', 'Status', 10),
    'Struggle': ('Normal', 'Physical', 1),
    'Sketch': ('Normal', 'Status', 1),
    'Triple Kick': ('Fighting', 'Physical', 10),
    'Thief': ('Dark', 'Physical', 10),
    'Spider Web': ('Bug', 'Status', 10),
    'Mind Reader': ('Normal', 'Status', 5),
    'Nightmare': ('Ghost', 'Status', 15),
    'Flame Wheel': ('Fire', 'Physical', 25),
    'Snore': ('Normal', 'Special', 15),
    'Curse': ('???', 'Status', 10),
    'Flail': ('Normal', 'Physical', 15),
    'Conversion 2': ('Normal', 'Status', 30),
    'Aeroblast': ('Flying', 'Special', 5),
    'Cotton Spore': ('Grass', 'Status', 40),
    'Reversal': ('Fighting', 'Physical', 15),
    'Spite': ('Ghost', 'Status', 10),
    'Powder Snow': ('Ice', 'Special', 25),
    'Protect': ('Normal', 'Status', 10),
    'Mach Punch': ('Fighting', 'Physical', 30),
    'Scary Face': ('Normal', 'Status', 10),
    'Faint Attack': ('Dark', 'Physical', 20),
    'Sweet Kiss': ('Normal', 'Status', 10),
    'Belly Drum': ('Normal', 'Status', 10),
    'Sludge Bomb': ('Poison', 'Special', 10),
    'Mud-Slap': ('Ground', 'Special', 10),
    'Octazooka': ('Water', 'Special', 10),
    'Spikes': ('Ground', 'Status', 20),
    'Zap Cannon': ('Electric', 'Special', 5),
    'Foresight': ('Normal', 'Status', 40),
    'Destiny Bond': ('Ghost', 'Status', 5),
    'Perish Song': ('Normal', 'Status', 5),
    'Icy Wind': ('Ice', 'Special', 15),
    'Detect': ('Fighting', 'Status', 5),
    'Bone Rush': ('Ground', 'Physical', 10),
    'Lock-On': ('Normal', 'Status', 5),
    'Outrage': ('Dragon', 'Physical', 15),
    'Sandstorm': ('Rock', 'Status', 10),
    'Giga Drain': ('Grass', 'Special', 10),
    'Endure': ('Normal', 'Status', 10),
    'Charm': ('Normal', 'Status', 20),
    'Rollout': ('Rock', 'Physical', 20),
    'False Swipe': ('Normal', 'Physical', 40),
    'Swagger': ('Normal', 'Status', 15),
    'Milk Drink': ('Normal', 'Status', 10),
    'Spark': ('Electric', 'Physical', 20),
    'Fury Cutter': ('Bug', 'Physical', 20),
    'Steel Wing': ('Steel', 'Physical', 25),
    'Mean Look': ('Normal', 'Status', 5),
    'Attract': ('Normal', 'Status', 15),
    'Sleep Talk': ('Normal', 'Status', 10),
    'Heal Bell': ('Normal', 'Status', 5),
    'Return': ('Normal', 'Physical', 20),
    'Present': ('Normal', 'Physical', 15),
    'Frustration': ('Normal', 'Physical', 20),
    'Safeguard': ('Normal', 'Status', 25),
    'Pain Split': ('Normal', 'Status', 20),
    'Sacred Fire': ('Fire', 'Physical', 5),
    'Magnitude': ('Ground', 'Physical', 30),
    'Dynamic Punch': ('Fighting', 'Physical', 5),
    'Megahorn': ('Bug', 'Physical', 10),
    'Dragon Breath': ('Dragon', 'Special', 20),
    'Baton Pass': ('Normal', 'Status', 40),
    'Encore': ('Normal', 'Status', 5),
    'Pursuit': ('Dark', 'Physical', 20),
    'Rapid Spin': ('Normal', 'Physical', 40),
    'Sweet Scent': ('Normal', 'Status', 20),
    'Iron Tail': ('Steel', 'Physical', 15),
    'Metal Claw': ('Steel', 'Physical', 35),
    'Vital Throw': ('Fighting', 'Physical', 10),
    'Morning Sun': ('Normal', 'Status', 5),
    'Synthesis': ('Grass', 'Status', 5),
    'Moonlight': ('Normal', 'Status', 5),
    'Hidden Power': ('Normal', 'Special', 15),
    'Cross Chop': ('Fighting', 'Physical', 5),
    'Twister': ('Dragon', 'Special', 20),
    'Rain Dance': ('Water', 'Status', 5),
    'Sunny Day': ('Fire', 'Status', 5),
    'Crunch': ('Dark', 'Physical', 15),
    'Mirror Coat': ('Psychic', 'Special', 20),
    'Psych Up': ('Normal', 'Status', 10),
    'Extreme Speed': ('Normal', 'Physical', 5),
    'Ancient Power': ('Rock', 'Special', 5),
    'Shadow Ball': ('Ghost', 'Special', 15),
    'Future Sight': ('Psychic', 'Special', 15),
    'Rock Smash': ('Fighting', 'Physical', 15),
    'Whirlpool': ('Water', 'Special', 15),
    'Beat Up': ('Dark', 'Physical', 10),
    'Fake Out': ('Normal', 'Physical', 10),
    'Uproar': ('Normal', 'Special', 10),
    'Stockpile': ('Normal', 'Status', 20),
    'Spit Up': ('Normal', 'Special', 10),
    'Swallow': ('Normal', 'Status', 10),
    'Heat Wave': ('Fire', 'Special', 10),
    'Hail': ('Ice', 'Status', 10),
    'Torment': ('Dark', 'Status', 15),
    'Flatter': ('Dark', 'Status', 15),
    'Will-O-Wisp': ('Fire', 'Status', 15),
    'Memento': ('Dark', 'Status', 10),
    'Facade': ('Normal', 'Physical', 20),
    'Focus Punch': ('Fighting', 'Physical', 20),
    'Smelling Salt': ('Normal', 'Physical', 10),
    'Follow Me': ('Normal', 'Status', 20),
    'Nature Power': ('Normal', 'Status', 20),
    'Charge': ('Electric', 'Status', 20),
    'Taunt': ('Dark', 'Status', 20),
    'Helping Hand': ('Normal', 'Status', 20),
    'Trick': ('Psychic', 'Status', 10),
    'Role Play': ('Psychic', 'Status', 10),
    'Wish': ('Normal', 'Status', 10),
    'Assist': ('Normal', 'Status', 20),
    'Ingrain': ('Grass', 'Status', 20),
    'Superpower': ('Fighting', 'Physical', 5),
    'Magic Coat': ('Psychic', 'Status', 15),
    'Recycle': ('Normal', 'Status', 10),
    'Revenge': ('Fighting', 'Physical', 10),
    'Brick Break': ('Fighting', 'Physical', 15),
    'Yawn': ('Normal', 'Status', 10),
    'Knock Off': ('Dark', 'Physical', 20),
    'Endeavor': ('Normal', 'Physical', 5),
    'Eruption': ('Fire', 'Special', 5),
    'Skill Swap': ('Psychic', 'Status', 10),
    'Imprison': ('Psychic', 'Status', 10),
    'Refresh': ('Normal', 'Status', 20),
    'Grudge': ('Ghost', 'Status', 5),
    'Snatch': ('Dark', 'Status', 10),
    'Secret Power': ('Normal', 'Physical', 20),
    'Dive': ('Water', 'Physical', 10),
    'Arm Thrust': ('Fighting', 'Physical', 20),
    'Camouflage': ('Normal', 'Status', 20),
    'Tail Glow': ('Bug', 'Status', 20),
    'Luster Purge': ('Psychic', 'Special', 5),
    'Mist Ball': ('Psychic', 'Special', 5),
    'Feather Dance': ('Flying', 'Status', 15),
    'Teeter Dance': ('Normal', 'Status', 20),
    'Blaze Kick': ('Fire', 'Physical', 10),
    'Mud Sport': ('Ground', 'Status', 15),
    'Ice Ball': ('Ice', 'Physical', 20),
    'Needle Arm': ('Grass', 'Physical', 15),
    'Slack Off': ('Normal', 'Status', 10),
    'Hyper Voice': ('Normal', 'Special', 10),
    'Poison Fang': ('Poison', 'Physical', 15),
    'Crush Claw': ('Normal', 'Physical', 10),
    'Blast Burn': ('Fire', 'Special', 5),
    'Hydro Cannon': ('Water', 'Special', 5),
    'Meteor Mash': ('Steel', 'Physical', 10),
    'Astonish': ('Ghost', 'Physical', 15),
    'Weather Ball': ('Normal', 'Special', 10),
    'Aromatherapy': ('Grass', 'Status', 5),
    'Fake Tears': ('Dark', 'Status', 20),
    'Air Cutter': ('Flying', 'Special', 25),
    'Overheat': ('Fire', 'Special', 5),
    'Odor Sleuth': ('Normal', 'Status', 40),
    'Rock Tomb': ('Rock', 'Physical', 10),
    'Silver Wind': ('Bug', 'Special', 5),
    'Metal Sound': ('Steel', 'Status', 40),
    'Grass Whistle': ('Grass', 'Status', 15),
    'Tickle': ('Normal', 'Status', 20),
    'Cosmic Power': ('Psychic', 'Status', 20),
    'Water Spout': ('Water', 'Special', 5),
    'Signal Beam': ('Bug', 'Special', 15),
    'Shadow Punch': ('Ghost', 'Physical', 20),
    'Extrasensory': ('Psychic', 'Special', 30),
    'Sky Uppercut': ('Fighting', 'Physical', 15),
    'Sand Tomb': ('Ground', 'Physical', 15),
    'Sheer Cold': ('Ice', 'Special', 5),
    'Muddy Water': ('Water', 'Special', 10),
    'Bullet Seed': ('Grass', 'Physical', 30),
    'Aerial Ace': ('Flying', 'Physical', 20),
    'Icicle Spear': ('Ice', 'Physical', 30),
    'Iron Defense': ('Steel', 'Status', 15),
    'Block': ('Normal', 'Status', 5),
    'Howl': ('Normal', 'Status', 40),
    'Dragon Claw': ('Dragon', 'Physical', 15),
    'Frenzy Plant': ('Grass', 'Special', 5),
    'Bulk Up': ('Fighting', 'Status', 20),
    'Bounce': ('Flying', 'Physical', 5),
    'Mud Shot': ('Ground', 'Special', 15),
    'Poison Tail': ('Poison', 'Physical', 25),
    'Covet': ('Normal', 'Physical', 40),
    'Volt Tackle': ('Electric', 'Physical', 15),
    'Magical Leaf': ('Grass', 'Special', 20),
    'Water Sport': ('Water', 'Status', 15),
    'Calm Mind': ('Psychic', 'Status', 20),
    'Leaf Blade': ('Grass', 'Physical', 15),
    'Dragon Dance': ('Dragon', 'Status', 20),
    'Rock Blast': ('Rock', 'Physical', 10),
    'Shock Wave': ('Electric', 'Special', 20),
    'Water Pulse': ('Water', 'Special', 20),
    'Doom Desire': ('Steel', 'Special', 5),
    'Psycho Boost': ('Psychic', 'Special', 5),
    'Roost': ('Flying', 'Status', 10),
    'Gravity': ('Psychic', 'Status', 5),
    'Miracle Eye': ('Psychic', 'Status', 40),
    'Wake-Up Slap': ('Fighting', 'Physical', 10),
    'Hammer Arm': ('Fighting', 'Physical', 10),
    'Gyro Ball': ('Steel', 'Physical', 5),
    'Healing Wish': ('Psychic', 'Status', 10),
    'Brine': ('Water', 'Special', 10),
    'Natural Gift': ('Normal', 'Physical', 15),
    'Feint': ('Normal', 'Physical', 10),
    'Pluck': ('Flying', 'Physical', 20),
    'Tailwind': ('Flying', 'Status', 30),
    'Acupressure': ('Normal', 'Status', 30),
    'Metal Burst': ('Steel', 'Physical', 10),
    'U-turn': ('Bug', 'Physical', 20),
    'Close Combat': ('Fighting', 'Physical', 5),
    'Payback': ('Dark', 'Physical', 10),
    'Assurance': ('Dark', 'Physical', 10),
    'Embargo': ('Dark', 'Status', 15),
    'Fling': ('Dark', 'Physical', 10),
    'Psycho Shift': ('Psychic', 'Status', 10),
    'Trump Card': ('Normal', 'Special', 5),
    'Heal Block': ('Psychic', 'Status', 15),
    'Wring Out': ('Normal', 'Special', 5),
    'Power Trick': ('Psychic', 'Status', 10),
    'Gastro Acid': ('Poison', 'Status', 10),
    'Lucky Chant': ('Normal', 'Status', 30),
    'Me First': ('Normal', 'Status', 20),
    'Copycat': ('Normal', 'Status', 20),
    'Power Swap': ('Psychic', 'Status', 10),
    'Guard Swap': ('Psychic', 'Status', 10),
    'Punishment': ('Dark', 'Physical', 5),
    'Last Resort': ('Normal', 'Physical', 5),
    'Worry Seed': ('Grass', 'Status', 10),
    'Sucker Punch': ('Dark', 'Physical', 5),
    'Toxic Spikes': ('Poison', 'Status', 20),
    'Heart Swap': ('Psychic', 'Status', 10),
    'Aqua Ring': ('Water', 'Status', 20),
    'Magnet Rise': ('Electric', 'Status', 10),
    'Flare Blitz': ('Fire', 'Physical', 15),
    'Force Palm': ('Fighting', 'Physical', 10),
    'Aura Sphere': ('Fighting', 'Special', 20),
    'Rock Polish': ('Rock', 'Status', 20),
    'Poison Jab': ('Poison', 'Physical', 20),
    'Dark Pulse': ('Dark', 'Special', 15),
    'Night Slash': ('Dark', 'Physical', 15),
    'Aqua Tail': ('Water', 'Physical', 10),
    'Seed Bomb': ('Grass', 'Physical', 15),
    'Air Slash': ('Flying', 'Special', 20),
    'X-Scissor': ('Bug', 'Physical', 15),
    'Bug Buzz': ('Bug', 'Special', 10),
    'Dragon Pulse': ('Dragon', 'Special', 10),
    'Dragon Rush': ('Dragon', 'Physical', 10),
    'Power Gem': ('Rock', 'Special', 20),
    'Drain Punch': ('Fighting', 'Physical', 5),
    'Vacuum Wave': ('Fighting', 'Special', 30),
    'Focus Blast': ('Fighting', 'Special', 5),
    'Energy Ball': ('Grass', 'Special', 10),
    'Brave Bird': ('Flying', 'Physical', 15),
    'Earth Power': ('Ground', 'Special', 10),
    'Switcheroo': ('Dark', 'Status', 10),
    'Giga Impact': ('Normal', 'Physical', 5),
    'Nasty Plot': ('Dark', 'Status', 20),
    'Bullet Punch': ('Steel', 'Physical', 30),
    'Avalanche': ('Ice', 'Physical', 10),
    'Ice Shard': ('Ice', 'Physical', 30),
    'Shadow Claw': ('Ghost', 'Physical', 15),
    'Thunder Fang': ('Electric', 'Physical', 15),
    'Ice Fang': ('Ice', 'Physical', 15),
    'Fire Fang': ('Fire', 'Physical', 15),
    'Shadow Sneak': ('Ghost', 'Physical', 30),
    'Mud Bomb': ('Ground', 'Special', 10),
    'Psycho Cut': ('Psychic', 'Physical', 20),
    'Zen Headbutt': ('Psychic', 'Physical', 15),
    'Mirror Shot': ('Steel', 'Special', 10),
    'Flash Cannon': ('Steel', 'Special', 10),
    'Rock Climb': ('Normal', 'Physical', 20),
    'Defog': ('Flying', 'Status', 15),
    'Trick Room': ('Psychic', 'Status', 5),
    'Draco Meteor': ('Dragon', 'Special', 5),
    'Discharge': ('Electric', 'Special', 15),
    'Lava Plume': ('Fire', 'Special', 15),
    'Leaf Storm': ('Grass', 'Special', 5),
    'Power Whip': ('Grass', 'Physical', 10),
    'Rock Wrecker': ('Rock', 'Physical', 5),
    'Cross Poison': ('Poison', 'Physical', 20),
    'Gunk Shot': ('Poison', 'Physical', 5),
    'Iron Head': ('Steel', 'Physical', 15),
    'Magnet Bomb': ('Steel', 'Physical', 20),
    'Stone Edge': ('Rock', 'Physical', 5),
    'Captivate': ('Normal', 'Status', 20),
    'Stealth Rock': ('Rock', 'Status', 20),
    'Grass Knot': ('Grass', 'Special', 20),
    'Chatter': ('Flying', 'Special', 20),
    'Judgment': ('Normal', 'Special', 10),
    'Bug Bite': ('Bug', 'Physical', 20),
    'Charge Beam': ('Electric', 'Special', 10),
    'Wood Hammer': ('Grass', 'Physical', 15),
    'Aqua Jet': ('Water', 'Physical', 20),
    'Attack Order': ('Bug', 'Physical', 15),
    'Defend Order': ('Bug', 'Status', 10),
    'Heal Order': ('Bug', 'Status', 10),
    'Head Smash': ('Rock', 'Physical', 5),
    'Double Hit': ('Normal', 'Physical', 10),
    'Roar Of Time': ('Dragon', 'Special', 5),
    'Spacial Rend': ('Dragon', 'Special', 5),
    'Lunar Dance': ('Psychic', 'Status', 10),
    'Crush Grip': ('Normal', 'Physical', 5),
    'Magma Storm': ('Fire', 'Special', 5),
    'Dark Void': ('Dark', 'Status', 10),
    'Seed Flare': ('Grass', 'Special', 5),
    'Ominous Wind': ('Ghost', 'Special', 5),
    'Shadow Force': ('Ghost', 'Physical', 5),
}

# Overworld weather IDs (include/constants/overworld_weather.h). IDs 32-36 are
# seasonal weather for specific maps, which the game resolves from the date.
WEATHER = {
    0: 'Clear', 1: 'Cloudy', 2: 'Rain', 3: 'Heavy rain', 4: 'Thunderstorm',
    5: 'Snow', 6: 'Heavy snow', 7: 'Blizzard', 8: 'Clear', 9: 'Ashfall',
    10: 'Sandstorm', 11: 'Hail', 12: 'Spirits', 13: 'Clear', 14: 'Fog',
    15: 'Deep fog', 16: 'Dark flash',
    32: 'Route 212 South (seasonal)', 33: 'Route 213 (seasonal)', 34: 'Route 216 (seasonal)',
    35: 'Acuity Lakefront (seasonal)', 36: 'Snowpoint City (seasonal)',
}

# Move priority (moves not listed are 0), from the decomp's res/moves/*/data.json.
# Higher goes first in a turn; speed decides within the same priority.
MOVE_PRIORITY = {
    'Helping Hand': 5, 'Magic Coat': 4, 'Snatch': 4, 'Detect': 3, 'Endure': 3,
    'Follow Me': 3, 'Protect': 3, 'Feint': 2, 'Aqua Jet': 1, 'Bide': 1,
    'Bullet Punch': 1, 'Extreme Speed': 1, 'Fake Out': 1, 'Ice Shard': 1,
    'Mach Punch': 1, 'Quick Attack': 1, 'Shadow Sneak': 1, 'Sucker Punch': 1,
    'Vacuum Wave': 1, 'Vital Throw': -1, 'Focus Punch': -3, 'Avalanche': -4,
    'Revenge': -4, 'Counter': -5, 'Mirror Coat': -5, 'Roar': -6, 'Whirlwind': -6,
    'Trick Room': -7,
}

# Type IDs as stored in a BattleMon (+0x24, +0x25), in the game's order.
TYPES = [
    'Normal', 'Fighting', 'Flying', 'Poison', 'Ground', 'Rock', 'Bug', 'Ghost', 'Steel', '???',
    'Fire', 'Water', 'Grass', 'Electric', 'Psychic', 'Ice', 'Dragon', 'Dark',
]

# Type matchups that aren't 1x: (attacking type, defending type) -> multiplier,
# from sTypeMatchupMultipliers in the decomp's src/battle/battle_lib.c. For a
# Pokemon with two types, the two multipliers are multiplied.
TYPE_CHART = {
    ('Normal', 'Rock'): 0.5, ('Normal', 'Steel'): 0.5, ('Normal', 'Ghost'): 0,
    ('Fighting', 'Normal'): 2, ('Fighting', 'Ice'): 2, ('Fighting', 'Poison'): 0.5,
    ('Fighting', 'Flying'): 0.5, ('Fighting', 'Psychic'): 0.5, ('Fighting', 'Bug'): 0.5,
    ('Fighting', 'Rock'): 2, ('Fighting', 'Dark'): 2, ('Fighting', 'Steel'): 2,
    ('Fighting', 'Ghost'): 0,
    ('Flying', 'Electric'): 0.5, ('Flying', 'Grass'): 2, ('Flying', 'Fighting'): 2,
    ('Flying', 'Bug'): 2, ('Flying', 'Rock'): 0.5, ('Flying', 'Steel'): 0.5,
    ('Poison', 'Grass'): 2, ('Poison', 'Poison'): 0.5, ('Poison', 'Ground'): 0.5,
    ('Poison', 'Rock'): 0.5, ('Poison', 'Ghost'): 0.5, ('Poison', 'Steel'): 0,
    ('Ground', 'Fire'): 2, ('Ground', 'Electric'): 2, ('Ground', 'Grass'): 0.5,
    ('Ground', 'Poison'): 2, ('Ground', 'Flying'): 0, ('Ground', 'Bug'): 0.5,
    ('Ground', 'Rock'): 2, ('Ground', 'Steel'): 2,
    ('Rock', 'Fire'): 2, ('Rock', 'Ice'): 2, ('Rock', 'Fighting'): 0.5,
    ('Rock', 'Ground'): 0.5, ('Rock', 'Flying'): 2, ('Rock', 'Bug'): 2, ('Rock', 'Steel'): 0.5,
    ('Bug', 'Fire'): 0.5, ('Bug', 'Grass'): 2, ('Bug', 'Fighting'): 0.5,
    ('Bug', 'Poison'): 0.5, ('Bug', 'Flying'): 0.5, ('Bug', 'Psychic'): 2,
    ('Bug', 'Ghost'): 0.5, ('Bug', 'Dark'): 2, ('Bug', 'Steel'): 0.5,
    ('Ghost', 'Normal'): 0, ('Ghost', 'Psychic'): 2, ('Ghost', 'Dark'): 0.5,
    ('Ghost', 'Steel'): 0.5, ('Ghost', 'Ghost'): 2,
    ('Steel', 'Fire'): 0.5, ('Steel', 'Water'): 0.5, ('Steel', 'Electric'): 0.5,
    ('Steel', 'Ice'): 2, ('Steel', 'Rock'): 2, ('Steel', 'Steel'): 0.5,
    ('Fire', 'Fire'): 0.5, ('Fire', 'Water'): 0.5, ('Fire', 'Grass'): 2, ('Fire', 'Ice'): 2,
    ('Fire', 'Bug'): 2, ('Fire', 'Rock'): 0.5, ('Fire', 'Dragon'): 0.5, ('Fire', 'Steel'): 2,
    ('Water', 'Fire'): 2, ('Water', 'Water'): 0.5, ('Water', 'Grass'): 0.5,
    ('Water', 'Ground'): 2, ('Water', 'Rock'): 2, ('Water', 'Dragon'): 0.5,
    ('Grass', 'Fire'): 0.5, ('Grass', 'Water'): 2, ('Grass', 'Grass'): 0.5,
    ('Grass', 'Poison'): 0.5, ('Grass', 'Ground'): 2, ('Grass', 'Flying'): 0.5,
    ('Grass', 'Bug'): 0.5, ('Grass', 'Rock'): 2, ('Grass', 'Dragon'): 0.5,
    ('Grass', 'Steel'): 0.5,
    ('Electric', 'Water'): 2, ('Electric', 'Electric'): 0.5, ('Electric', 'Grass'): 0.5,
    ('Electric', 'Ground'): 0, ('Electric', 'Flying'): 2, ('Electric', 'Dragon'): 0.5,
    ('Psychic', 'Fighting'): 2, ('Psychic', 'Poison'): 2, ('Psychic', 'Psychic'): 0.5,
    ('Psychic', 'Dark'): 0, ('Psychic', 'Steel'): 0.5,
    ('Ice', 'Water'): 0.5, ('Ice', 'Grass'): 2, ('Ice', 'Ice'): 0.5, ('Ice', 'Ground'): 2,
    ('Ice', 'Flying'): 2, ('Ice', 'Dragon'): 2, ('Ice', 'Steel'): 0.5, ('Ice', 'Fire'): 0.5,
    ('Dragon', 'Dragon'): 2, ('Dragon', 'Steel'): 0.5,
    ('Dark', 'Fighting'): 0.5, ('Dark', 'Psychic'): 2, ('Dark', 'Ghost'): 2,
    ('Dark', 'Dark'): 0.5, ('Dark', 'Steel'): 0.5,
}
# The Normal/Fighting-on-Ghost immunities, which Foresight (and Odor Sleuth) turn off.
FORESIGHT_IGNORES = {('Fighting', 'Ghost'), ('Normal', 'Ghost')}

# BattleMon statBoosts (+0x18, 8 x s8, 0-12 with 6 = unchanged), in order.
# The first (HP) is never used.
STAT_STAGES = ['HP', 'ATK', 'DEF', 'SPE', 'SPA', 'SPD', 'ACC', 'EVA']

# BattleMon statusVolatile (+0x70) bits worth showing, from the decomp's
# include/constants/battle/condition.h: name -> mask.
VOLATILE_CONDITIONS = {
    'Confused': 0x7, 'Infatuated': 0xF << 16, 'Substitute': 1 << 24,
    'Nightmare': 1 << 27, 'Cursed': 1 << 28, 'Identified': 1 << 29,
}
# BattleMon moveEffectsMask (+0x80) bits worth showing
# (include/constants/battle/moves.h).
MOVE_EFFECTS = {'Leech Seed': 1 << 2}
